### ISSUE TITLE
Angularjs inner prism

### ISSUE THREAD

**Issue by thiaguerd** [PrismJS/prism#1017]
``` html
<label>Your app path:</label>
<input type="text" ng-model="app_path" placeholder="path" class="form-control dib">
```

``` html
<pre class="language-ruby line-numbers"><code prism>
working_directory "{{app_path}}"
</code></pre>
```

``` html
<pre class="language-nginx line-numbers unescaped"><code>
server {
    listen         80;
    server_name    localhost;

    root {{app_path}}/public;
}
</code></pre>
```

not work :(

**Comment by Golmote** [comment]
Could you provide an online example of your not working code?

**Comment by thiaguerd** [comment]
https://jsfiddle.net/rckwnhx1/

**Comment by Golmote** [comment]
I'm not familiar with Angular but, because Prism overrides the contents of the elements containing your Angular placeholders, I'm pretty sure you need to manually trigger the highlighting again anytime you model's data change, so that Prism highlights the updated code.
Hopefully, Angular provides that kind of feature...
