### ISSUE TITLE
<?php tag breaks line numbers

### ISSUE THREAD

**Issue by ghost** [PrismJS/prism#1018]
In php code preview line numbers break when I add <?php tag.

Here is example by Gabriel Luethje(we have the same issue):
https://codepen.io/FStop/pen/rCBaJ?editors=1111

When "?" in opening php tag is removed the line number works fine.

**Comment by Golmote** [comment]
Hi, thanks for reporting.

It looks like I was wrong in #998. We _do_ need to store and restore the original code for the line-numbers plugin to work properly.
Doing so, though, creates an issue when used with the remove-initial-line-feed or the normalise-whitespace plugins. This is because those plugins need to run _before_ the `before-highlight` hook. Moving them to the `before-sanity-check` hook appears to solve the problem.
