### ISSUE TITLE
UX: Download page

### ISSUE THREAD

**Issue by leoarnold** [PrismJS/prism#1038]
**Confusion:** On the [download page](http://prismjs.com/download.html) I tried to download Prism files with the _Okaida_ theme, but the downloaded files would always provide the default theme.

**Root cause:** There are two _independent_ theme selectors: one will set the theme displayed, the other the theme in the files to be downloaded.

**Suggestion:** Synchronize the two selectors or redesign to one selector in order to make the page more "WYSIWYG".

**Comment by Golmote** [comment]
@LeaVerou Here are suggestions for label names, taken from https://github.com/MunGell/awesome-for-beginners:

- `first-timers-only` (it's popular, but I'm not a big fan of it, since it _prevents_ anyone more experienced from fixing the issue, which I think is stupid)
- `good first issue`, `good-beginner-issue`, `good-for-beginner`, `easy-pick`, `first timers welcome`, `good-first-contribution`, `beginner-friendly`
- `beginner`, `Level:Starter`, `exp/beginner`, `difficulty/newcomer` (which implies, I suppose, creating other labels for other levels of estimated difficulty)
