### ISSUE TITLE
language-ini uses "important" class

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#1044]
For INI sections such as `[foo]`, the `language-ini` plugin adds things like:

``` html
<span class="token important">[foo]</span>
```

The problem is that I'm already using a stylesheet that defines something for the `important` CSS class, so my INI file listings now have icons before the sections such as `[foo]`.

I could fiddle around with my CSS stylesheets to work around this issue, but I'm curious --- why was the CSS class "important" used? How is "important" semantically related to an INI section? Wouldn't the CSS class "ini-section" have made more sense (and have less chance of clashing with user stylesheet classes)?

I'm asking more than being critical, to see if there is a good reason. Is this something we could improve?

This is one of the last things on my list of things today, so I apologize for any errors or oversights from my sleepy mind.

**Comment by LeaVerou** [comment]
You can use descendant selectors, like `code.language-css .important` and `code.language-ini .important`.

**Comment by garretwilson** [comment]
I'm unclear if you are suggesting that I use these selectors, or that the author of the `language-ini` plugin use these selectors. Either way there is a problem. The INI section headers are getting my style for my general `important` class, which I do _not_ want to happen.

I don't think that the `language-ini` class should be adding such a general word such as `important` to the markup. It would be so easy to clash with somebody else's semantics for "important". Besides, the semantics for the word "important" don't even match here --- how is an INI section header more "important" than anything else in an INI file?

Wouldn't it be more appropriate to use a word such as "ini-section"? Isn't that more semantically correct? It has much less chance of getting the styles applied from some user's "important" class.

**Comment by LeaVerou** [comment]
I was suggesting that you use these selectors to style `.important` in CSS and INI blocks differently.

We try to reuse classes otherwise the CSS files would be unmaintainable. Agreed though that `important` seems an odd choice. @aviaryan, perhaps you can explain your rationale on picking that? Is there something more appropriate?

**Comment by aviaryan** [comment]
@LeaVerou Sorry. I haven't been in touch with the Prism codebase lately. I found the commit which has the change. https://github.com/PrismJS/prism/commit/706774950563df643dc39fb51601dba38b0f8dc9 
As far as I think, I may have added the important class because `attr-value` would also match section names like `[section=name=with=equals]`. I am not sure if this is an issue now or not. I will check and reply back. Rest assured, I will remove the `important` token in whatever way possible.

**Comment by aviaryan** [comment]
Opened PR #1047

**Comment by garretwilson** [comment]
Thank you for looking into this, @aviaryan .
