### ISSUE TITLE
Exception when run in a WebWorker

### ISSUE THREAD

**Issue by ligaz** [PrismJS/prism#1059]
Trying to execute `Prism.highlight(...)` in a WebWorker results in an error being throw from Prism. 

It looks like the [following code](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-core.js#L465-L473) is the culprit. It assumes that if Prism is run in a Worker it will a be Worker created by itself using the `async` option and the message will have the Prism contract being a JSON with `language`, `code` and `immediateClose` fields.

**Comment by Golmote** [comment]
Can you provide some example code to reproduce the issue? Prism should be able to be used in a Worker. I just tested the following code, that works:

```javascript
	var worker = new Worker('prism.js');
	worker.onmessage = function(evt) {
		console.log(evt.data);
		// Displays <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>span</span><span class="token punctuation">></span></span>
	};
	worker.postMessage(JSON.stringify({
		language: 'markup',
		code: '<span>'
	}));
```

**Comment by Rob--W** [comment]
@Golmote Look at [the code linked from the report](https://github.com/PrismJS/prism/blob/025147106e82b6efa92ba947cc06cc1a838f477b/components/prism-core.js#L465-L473). It is quite obvious that it unconditionally handles any messages. That makes Prism.js in its current form unsuitable *as a library in a Web worker* (opposed to being the sole and only script running in the worker, as the code currently assumes). 

I worked around the issue in my own project by temporarily clearing the `addEventListener` method because then prism.js will not attach a global message listener ([ref in prism source](https://github.com/PrismJS/prism/blob/025147106e82b6efa92ba947cc06cc1a838f477b/components/prism-core.js#L459-L462)): https://github.com/Rob--W/crxviewer/blob/ce1c9ec1bd5dc61f6d302ba835b76c16418d9ac0/src/lib/prettify/prism-source-extensions.js#L8-L14

Ideally there would be a global flag to disable this, e.g. `_self.prismAsWorkerLib` (if this is set, then Prism.js will not attach a `message` handler).

**Comment by Golmote** [comment]
Could we add a public method to detach the message listener? Would this help?

**Comment by ligaz** [comment]
Ideally the `onmessage` handler should be installed in case `Prism.highlightElement` is run with `async` option: https://github.com/PrismJS/prism/blob/gh-pages/components/prism-core.js#L212

**Comment by ligaz** [comment]
You can also check the format of the incoming message and do nothing if it cannot be processed.

**Comment by Rob--W** [comment]
> Ideally the `onmessage` handler should be installed in case `Prism.highlightElement` is run with `async` option: https://github.com/PrismJS/prism/blob/gh-pages/components/prism-core.js#L212

The `onmessage` handler must be registered in the worker, not in the main thread, so this does not work unless you plan on creating a dynamic worker script.

**Comment by ligaz** [comment]
@Rob--W True that. There are ways to hack this around (like passing arguments via location) but they are not stable.
