### ISSUE TITLE
[Autoloader + Line Highlight] Extra space at the end

### ISSUE THREAD

**Issue by dlecina** [PrismJS/prism#1101]
There seems to be some sort of compatibility issue between Autoloader and Line Highlight. Here's what my code looked like before using Autoloader:

![Before](http://i.imgur.com/uFUJNbm.png)

Here's what it looks like when using it:

![After](http://i.imgur.com/fjBc1aS.png)

No extra space is added when I don't use Line highlight:

![No line highlight](http://i.imgur.com/E3GSch7.png)

I took a look at the HTML after the Prism pass and it looks like extra whitespace is being added for no clear reason (i.e. this is not a CSS issue).

Thank you for your time.

**Comment by zeitgeist87** [comment]
Thank you for reporting this. It should be fixed now [79b723d](https://github.com/PrismJS/prism/commit/79b723dca9e4ac9244e2859c5507afe3e32bb4d4)

The problem was, that `line-highlight` appends a few tags to the `<code>` tag. These tags contain whitespace, which is later picked up by the `autoloader` plugin with the `textContent` property and interpreted as normal source code.
