### ISSUE TITLE
"var-1" is divided incorrectly into "var" and "-1"

### ISSUE THREAD

**Issue by s3131212** [PrismJS/prism#1110]
In Python mode (not sure whether this bug also exist in other language), `var-1` should be divided into `var` (variable, which will be a text node after parsing), `-` (operator) , and `1` (number) . However, when there is no space between "-" and "1", the string will be divided into `var` and `-1`(number).

![image](https://cloud.githubusercontent.com/assets/4427280/23861310/9caafea2-0844-11e7-9c8a-dbc040a4db1e.png)

**Comment by s3131212** [comment]
After some more trying, I believe the problem might be, it can't inspect the negative number :(
![image](https://cloud.githubusercontent.com/assets/4427280/23864222/cc9a1b0e-084c-11e7-9a1a-6ea6e6a1b660.png)

**Comment by LeaVerou** [comment]
Could you provide a bit more context? Where does `var-1` appear in your code? Pasting a bigger code snippet that contains this would help…

**Comment by s3131212** [comment]
```python
input = -1    # "-1" should be a number
input = input - 1     # "-1" should be divided into "-" and "1"
```

Also, after some researching, I found out that there are the similar issue ( #810 ) already. Is this there any plan to deal with this problem or still remain the decision made by [Golmote](https://github.com/PrismJS/prism/issues/810#issuecomment-148298003) ?
Thanks a lot and sorry for my poor English.

**Comment by kylekatarnls** [comment]
As you can see here, the highlighting in GitHub also consider `-` as an operator in front of `1`. To me, it's not different from `!1` or `~1` or `-input`. Except maybe when you do: `input - -1`, here we really have operator then `-1`. So my opinion is: works as expected.

**Comment by LeaVerou** [comment]
I disagree, negative numbers are numbers, not an operator and a number. It's very easy to convert our number regexes to include signed numbers, in fact I'm surprised they don't already. @Golmote, @zeitgeist87 what do you guys think?

**Comment by zeitgeist87** [comment]
The behavior is a bit inconsistent. The problem is, that the `number` definition for most languages begins with the following regex `\b-?`. The minus sign can also be a word boundary at the same time and `\b` is a zero-length match. This complicates things a bit:

* Case `word -1`: The zero-length `\b` matches between `-` and `1` because `-` is seen as a word boundary. So `-` will become an operator and `1` will be a number.
* Case `word-1`: The `\b` matches the end of `word` between `d` and `-`. This time `-` is part of the number.

We could make it more consistent and remove all `-?` from the `number` definitions of all regexes. Then it would always be an operator.

**Comment by LeaVerou** [comment]
What if we convert it to `(?:\B-|\b)`?

**Comment by Golmote** [comment]
I'm pretty sure this regexp is used in at least one component in Prism, though I'm not on a computer to do a full search on the project. But I have a terrible memory so maybe I'm wrong... 
Nevertheless, if it works as expected, I don't mind using it.

**Comment by zeitgeist87** [comment]
How about `(?:-|\b)`? I couldn't find any case where it would not work, but maybe I am missing something. @LeaVerou What is the `\B` for?

**Comment by LeaVerou** [comment]
`(?:-|\b)` would fail with prefix decrement operators like `--i;`.
`\B` is the opposite of `\b`: `\b` matches at a word boundary, e.g. non-word character before a word character. `\B` matches a non-word boundary, i.e. when both characters are of the same type, either both word characters or both non-word characters. Since `-` is a non-word character, it would match it when it’s after another non-word character. Now that I think about it, that would also fail for `--i;`. Sigh :(

**Comment by Golmote** [comment]
Haha we might get back to what I was saying in #810 in the end. Always highlight as operator + number...

**Comment by LeaVerou** [comment]
Yeah, or use lookbehind… Sigh, lookbehind in regexps cannot come fast enough :(

**Comment by zeitgeist87** [comment]
I think we should accept, that we can never make it semantically correct using only regular expressions:

```js
i = i -1; // Operator 
i = -1; // Negative number
```

The simplest solution would be to always highlight as an operator. It wouldn't be a big change either, because we are already more than half way there:

![operator](https://cloud.githubusercontent.com/assets/1210795/24320099/90ff2cd4-112e-11e7-9149-5f338c2de66f.png)

**Comment by LeaVerou** [comment]
Ok! Would probably simplify some regexps too :)
