### ISSUE TITLE
Support for ligatures?

### ISSUE THREAD

**Issue by FezVrasta** [PrismJS/prism#1133]
Hi, I see that if I write `=>` it gets converted in:

```
<span class="token operator">=</span>
<span class="token operator">></span>
```

But this breaks the ligature of the font I'm using (Fira Code).

Could it be possible to group together tokens of the same type to allow ligatures?
Ideally the markup should be:

```
<span class="token operator">=></span>
```

**Comment by Golmote** [comment]
Hi, what language are you highlighting?

**Comment by FezVrasta** [comment]
JavaScript.

**Comment by Golmote** [comment]
Thanks for reporting. This should be fixed now.

**Comment by hax** [comment]
@Golmote  Could you publish a new version?

**Comment by ManuelRauber** [comment]
Is this really fixed?

![image](https://user-images.githubusercontent.com/740791/44212858-c2b54680-a16c-11e8-89d9-b05c2a6d5d60.png)

Seems not to work for C# code

**Comment by RunDevelopment** [comment]
Well, it is fixed in JavaScript but not C#.

The title is kind of ambiguous.

**Comment by dsvensson** [comment]
@Golmote Same applies to Rust, `::` at least.. perhaps more.

**Comment by RunDevelopment** [comment]
@dsvensson Does this also apply for other Rust operators?
I found that the `..` operator has the same problem and wanted to ask whether there are other multi-character operators in Rust.

**Comment by dsvensson** [comment]
@RunDevelopment Nice... the documentation actually has a complete table of all operators, https://doc.rust-lang.org/book/appendix-02-operators.html

**Comment by VFDan** [comment]
`=>` isn't the only operator in JavaScript with ligatures; `??` exists, and many others. I think that this could break the way Prism works though...

**Comment by RunDevelopment** [comment]
@VFDan 
Prism generally captures operators as a whole even if composed of several characters. E.g. `...`, `=>`, and `??` will all be matched as [one token](https://github.com/PrismJS/prism/blob/master/tests/languages/javascript/operator_feature.test). This requires some maintenance but is also more useful when processing Prism's token stream because Prism has some real understanding of the code. A neat little side-effect is that font ligature is natively supported.

Point is: ligatures breaking is usually just a sign that Prism tokenization isn't correct.
