### ISSUE TITLE
Is it possible to highlight with the "marked" markdown parser?

### ISSUE THREAD

**Issue by myst729** [PrismJS/prism#1192]
https://github.com/chjj/marked#highlight

I'd like to use prism together with marked, to render markdown in the browser. Any ideas?

**Comment by Golmote** [comment]
It looks like it is, as long as the correct grammars are loaded first.

```js
marked.setOptions({
	highlight: function (code, lang) {
		return Prism.highlight(code, Prism.languages[lang], lang);
	}
});
```

**Comment by myst729** [comment]
If someone writes markdown code block without specifying the language, it fails.

<pre>
```
some unknown code here
```
</pre>

Now I get rid of it by fallback to `markup`, any better ideas?

```js
function (code, lang) {
  return prism.highlight(code, prism.languages[lang || 'markup'])
}
```

BTW, I found **highlight.js** provides an "auto" method to predict the language.

**Comment by Golmote** [comment]
Prism has no way to autodetect the language currently. And it's not planned afaik.
I guess you could also fallback to doing no highlighting whatsoever when the language is not specified.

**Comment by aegatlin** [comment]
I am using the `marked` options key `highlight` function and it does not add the appropriate class to the `<pre>` tags for code blocks. `<code>` tags have the appropriate class, but not the `<pre>` tags that wrap them.

This is a problem for Prism because it claims that classes with no `<pre>` tag class is fine. From the Prism website:

```
If you use that pattern, the <pre> will automatically get the language-xxxx class (if it doesn’t already have it) and will be styled as a code block.
```

This is not occurring when I'm using Prism with `marked`. I am defining the behavior inside a React component `.tsx` file. Here is my code:

```html
return (
    <Layout title={title}>
      <div
        className={postWrapper}
        dangerouslySetInnerHTML={{
          __html: marked(md, {
            highlight: (code, lang) => {
              // @ts-ignore
              return window.Prism.highlight(
                code,
                // @ts-ignore
                window.Prism.languages[lang],
                'typescript'
              )
            }
          })
        }}
      ></div>
    </Layout>
```

**Comment by chiefgunner** [comment]
```js
marked.setOptions({
  highlight: function(code, lang) {
    if (prism.languages[lang]) {
      return prism.highlight(code, prism.languages[lang], lang);
    } else {
      return code;
    }
  }
});
```

**Comment by RunDevelopment** [comment]
@chiefgunner This `highlight` function is dangerous. Prism will always return HTML source code meaning that all special HTML characters (`<`, `&`) will be escaped. In your case, this function can give you a good case of XSS depending on whether Prism supports a specific language. 
You can use `Prism.util.encode(someString)` to escape all special HTML characters.

**Comment by deepjyoti30** [comment]
@aegatlin I had the same issue of the `<pre>` tag not getting the proper language class and breaking the whole code highlight thing. It happened with NuxtJS.

In order to fix it, just `watch` the change in the component and call the `highlightAll` method again once something has changed.

In my case, when a new component (the one that contains the text being rendered) was mounted, the code wasn't highlighted, though it would work everytime I would refresh the page, so I simply added a bit of code to watch the component being mounted:

```js
// Watch the component mounted
mounted() {
    // Run PrismJS highlight again
    Prism.highlightAll()
}
```
