### ISSUE TITLE
Embedded HTML in JavaScript/TypeScript

### ISSUE THREAD

**Issue by mattdsteele** [PrismJS/prism#1198]
I know JavaScript inside HTML is supported, but is the inverse true? For example, say I'm writing an Angular component:

```typescript
import { Component } from '@angular/core';

@Component({
    selector: 'my-component',
    template: `
    <h2>Some Test Code</h2>
    `
})
```

Is there a way to have the `template` string be recognized as HTML, and highlighted as such?

**Comment by Golmote** [comment]
Hi @mattdsteele. This is tricky. JS can easily be supported inside HTML because it is explicitely identified as JS (with `<script>` tags). Here, your string could contain absolutely any language Prism supports, and there is no way for it to identify which one. I don't think Prism will provide support for this feature.

**Comment by mattdsteele** [comment]
Yeah, that makes sense. Thanks for considering!
