### ISSUE TITLE
API for different renderer

### ISSUE THREAD

**Issue by jcubic** [PrismJS/prism#1213]
Is there an API that allow to render different output? for instance I use prism to create [prism-cli](https://github.com/jcubic/prism-cli). I've check the source code for prism and monkey patch [_.Token.stringify](https://github.com/jcubic/prism-cli/blob/master/prism.js#L39) to output ANSI escape codes, is the better way to do this?

**Comment by Golmote** [comment]
Hi! Couldn't you use the `wrap` hook to do this?

**Comment by jcubic** [comment]
Looking at the source code, `_.hooks.run('wrap', env);` is called but result of it it's not returned by Token.stringify and it always return html.

**Comment by Golmote** [comment]
Oooh ok, I see the issue, sorry. I guess you could override `Prism.Token.stringify` from the outside without having to modify the original code.

You idea is interesting though. Maybe there is too much logic done there and we should have a function dedicated just to the `return` part of this function, so that there is less to override. That could be a first step towards a more generic approach to renderers.

**Comment by Golmote** [comment]
Actually, I played around a bit with this idea, and I realized it is much more powerful to override `Prism.highlight()` or manually call `Prism.tokenize()` and process the result. This is IMO the best way to achive this sort of custom rendering.
