### ISSUE TITLE
Line numbers not the same height as code

### ISSUE THREAD

**Issue by Ma-XX-oN** [PrismJS/prism#1231]
![image](https://user-images.githubusercontent.com/10625935/33160311-3d0a0c8c-cfe9-11e7-974a-027ae911c693.png)

This can be seen on my [blog](http://adrians-musings.blogspot.ca/2017/11/c-templates-how-to-effectively-and.html).

**Comment by Golmote** [comment]
I'm not exactly sure why, but it appears the "courier new" font-family that you have on a `span {` rule somewhere in your styles messes up with the rendering height of your code.

If you really want to apply this font to your code blocks, you should consider applying on the `code` elements, so that the line-height stays consistent.

**Comment by Ma-XX-oN** [comment]
Hi @Golmote,

Can you give me a location?  Or how you found that this was so, so that I can find this issue?

**Comment by Ma-XX-oN** [comment]
One other thing:
![image](https://user-images.githubusercontent.com/10625935/33192577-8340bd6a-d091-11e7-8682-cc1a78e9a96e.png)
If you notice, the numbers are slightly higher then the line it is referring to.  It is very noticeable on the bottom, but is also there on all of the other lines.  What's gong on?

**Comment by Golmote** [comment]
Yes, the one you commented out was the one I was refering to.

Can you try also adding a `display: block` on the selector `pre.line-numbers > code`?

**Comment by Ma-XX-oN** [comment]
Seems to be better:

![image](https://user-images.githubusercontent.com/10625935/33227160-11e2cea8-d16b-11e7-8f6e-96b839cd326e.png)
Though I think it might be better down one or more more pixels.

**Comment by Golmote** [comment]
You can adjust the styling if you want. But I can confirm lines and codes are actually aligned on your online version.

![https://i.imgur.com/oORZqVk.png](https://i.imgur.com/oORZqVk.png)

**Comment by Ma-XX-oN** [comment]
Oh, you're right.  Nm.  Thanks.

Why did I need to add a "display: block on the selector pre.line-numbers > code".  Is the CSS from my blog interfering with the one for the line numbers?

**Comment by Golmote** [comment]
Hi, sorry for the delay.
Because `code`s are `inline` by default, their total height is not exactly `line-height * number of lines`, leading to some mispositioning of the elements holding the line numbers.

I think the fact that you use `line-height: 1` instead of our default `1.5` on `code`s and `pre`s somehow increases the visual difference and makes the problem easier to spot in your use case.

**Comment by Golmote** [comment]
I'm closing this issue, since your specific use case is fixed, and #1132 already describes this problem more generally.
