### ISSUE TITLE
Using the same pattern inside regex

### ISSUE THREAD

**Issue by raulviitor1** [PrismJS/prism#1306]
Hello, 

I have a language that can contain [X [X]] and I need somehow do a push and pop with the brackets to be able right tokenize the language.

How I can do this in the prism JavaScript or in pattern ?

**Comment by raulviitor1** [comment]
To exemplify my doubt, I need to make this recursive.

I can accept:

[X [X]]

also accept

[X [X [X]]]

etc

**Comment by raulviitor1** [comment]
I looked in ruby example that has insertBefore and pattern with interpolation. It may help but I didn't understand this function.

**Comment by Golmote** [comment]
Hi! There is no real solution to make it infinitely recursive, because JS regexps can't do this.

The better you can do might be to allow for a certain number of recursion levels. With your square brackets example, that would be something like:
One level deep: `/\[[^\[\]]+\]/` will match `[X]`
Two levels deep: `/\[(?:\[[^\[\]]+\]|[^\[\]])+\]/` will match `[X[X]]`
Three levels deep: `/\[(?:\[(?:\[[^\[\]]+\]|[^\[\]])+\]|[^\[\]])+\]/` will match `[X[X[X]]]`

**Comment by CoenraadS** [comment]
`\[([^[\]]|(?R))*\]`

**Comment by Golmote** [comment]
@CoenraadS Yes, PHP does have recursive patterns. But we're doing JS here. ^^

**Comment by rednoah** [comment]
@Golmote thanks for the idea!

I was able to build a `{...}` nested language like so:
```
Prism.languages.format = {
	'expression-1': {
		pattern: /{[^{}]+}/,
		greedy: true,
		inside: Prism.languages.groovy
	},
	'expression-2': {
		pattern: /{(?:{[^{}]+}|[^{}])+}/,
		greedy: true,
		inside: Prism.languages.groovy
	},
	'expression-3': {
		pattern: /{(?:{(?:{[^{}]+}|[^{}])+}|[^{}])+}/,
		greedy: true,
		inside: Prism.languages.groovy
	}
};
```
Support for up to 3 nested `{{{}}}` is good enough for my use case.
