### ISSUE TITLE
Syntax highlighting javascript fails in markup mode if it highlights each line

### ISSUE THREAD

**Issue by paladox** [PrismJS/prism#1325]
Hi, if you use prism.highlight to highlight each line instead of all at once, the javascript mode in markup fails to highlight anything within <script> as it would not kick in that it is javascript, instead it thinks it is html still.

See https://codepen.io/anon/pen/EQJQjL

@ gerrit (using the new polygerrit ui) it highlights each line.

highlight.js worked.

**Comment by paladox** [comment]
Same for css too.

**Comment by paladox** [comment]
Yep, confirmed that by them adding .top in the value, it fixed the problem in highlight.js (that's if you do)

state.baseContext = result.top; after it.

**Comment by paladox** [comment]
cc @Golmote

**Comment by paladox** [comment]
https://github.com/isagalaev/highlight.js/commit/bc42f1b6955793fb98c6a4e92a024fa9e0f54375

**Comment by Golmote** [comment]
Please use the "Edit" option on your comments instead of commenting multiple times in a row.

I understand your issue now, and I see how highlight.js implemented a solution for it. That being said, Prism does not really work the same way, so I'm not sure it would be doable.
Knowing what was "parsed" in the lines before the one we want to highlight is one thing, but Prism might need to know what comes _after_ the current line. And I don't see how we could circumvent this.

**Comment by paladox** [comment]
oh, i will use the edit button next time (sorry about that).

And oh.

**Comment by paladox** [comment]
Seems prism.js is better at highlighting then highlight.js :).

I really like the colours + that it highlights functions and params better.

/me just wishes there was a way for it to look ahead like highlight.js
