### ISSUE TITLE
JSX not parsed correctly when using spread syntax

### ISSUE THREAD

**Issue by ericgio** [PrismJS/prism#1334]
Using spread syntax to apply props to a React component is a pretty common pattern. However, it doesn't look like the JSX language parser recognizes this:

![image](https://user-images.githubusercontent.com/2978513/37059473-6ca76f70-2142-11e8-83c9-f9677b408d20.png)

**Comment by Golmote** [comment]
Hi! Thanks for reporting. I couldn't reproduce your issue on the [Test page](http://prismjs.com/test.html) with the following code:

```jsx
<div style={{height: '300px'}}>
    <Typeahead
        {...this.state}
        labelKey="name"
        options={options}
        placeholder="Choose a state..."
    />
</div>
```

![https://i.imgur.com/kevscVn.png](https://i.imgur.com/kevscVn.png)

Please make sure you're using the latest version of Prism. If the issue is still relevant after that, please provide us with an online example reproducing it.

**Comment by ericgio** [comment]
You're right, I must have been using an older version of the JSX package. Thanks for pointing me to the testing page as well, I'll go there first next time.
