### ISSUE TITLE
Where to see the dependency between languages ?

### ISSUE THREAD

**Issue by kid-wumeng** [PrismJS/prism#1344]
Thinks the good library ~

I learn about the four basic components in document: markup, css, clike, javascript. Is it means other languages will depend on the four components ?

My work currently is write a document generating tools and it can let developers select highlight languages for they requirement. So I tried to build the minimum core by the Prism, in fact only import the prism-core and pack to bundle.js by Rollup. 

However happened the error when I try to import the prism-javascript. Then resolved by import clike before. Therefore, if a way or page to display the dependency between languages? I think should tell my customers where found the information.

**Comment by Golmote** [comment]
Hi!

I'm afraid at the moment the best place to find a list of the dependencies is the [`components.js`](https://github.com/PrismJS/prism/blob/gh-pages/components.js) file, which is far from convenient.

Regarding your use case, I think you should take a look at the [Autoloader plugin](http://prismjs.com/plugins/autoloader/), because it will take care of the dependencies for you.

I'll let this issue open to remind us we need to generate the full list of dependencies somewhere on the website.

**Comment by Golmote** [comment]
@kid-wumeng I just updated the [Examples](http://prismjs.com/examples.html) page. It know displays the dependencies for each language, if any.

![bur5mdi](https://user-images.githubusercontent.com/565460/37252179-371bcf02-251d-11e8-89d8-f252cfceaf39.png)

**Comment by kid-wumeng** [comment]
@Golmote Think you very much!
