### ISSUE TITLE
"after-tokenize" hook is not executed when call api Prims.tokenize()

### ISSUE THREAD

**Issue by supnate** [PrismJS/prism#1376]
I see in the pr https://github.com/PrismJS/prism/pull/1357 the hook "after-tokenize" is only called in `highlight()`. Could it be called in `tokenize()` instead? So that I could get right tokens when using the api. Thanks!

**Comment by Golmote** [comment]
Hi! No, it can't be called in `tokenize()` directly, since `tokenize()` is being called inside those hooks in the [`markup-templating`](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-markup-templating.js#L61) component.

But you can execute de hooks yourself, like it's currently done in the test runner: https://github.com/PrismJS/prism/blob/gh-pages/tests/helper/test-case.js#L65-L72

**Comment by supnate** [comment]
Ah, just realized the hook name is after-"tokenize". I can call it myself, thanks for the information!
