### ISSUE TITLE
Version 1.14.0 crashes when used in Spectacle

### ISSUE THREAD

**Issue by sslotsky** [PrismJS/prism#1394]
Version 1.14.0 appears to have introduced a [breaking change to spectacle](https://github.com/FormidableLabs/spectacle/issues/512), which I initially reported to them but probably really belongs here.

The prism portion of the stacktrace:

```
Uncaught TypeError: Cannot read property 'buildPlaceholders' of undefined
    at prism-handlebars.js:30
    at Object.run (prism-core.js:451)
    at highlight (prism-core.js:280)
```

Apparently introduced [in this commit](https://github.com/PrismJS/prism/commit/5f9c078a10237699aa0a6268903ecdae10bd7f4c).

Please let me know if I can provide any more information. Many thanks for the time and effort.

**Comment by Golmote** [comment]
The dependency for PHP has changed in #1367. You need to include the component `markup-templating` in addition to `c-like` (and probably `markup` depending on your use case).

**Comment by sslotsky** [comment]
Thanks for the reply @Golmote . I'm not totally sure I understand the suggestion. Are you saying that projects that use prism now have additional peer dependencies to satisfy? This seems like a breaking change for consumers of this library, should there have been a major version bump? Perhaps I'm misunderstanding what the issue is?

**Comment by mAAdhaTTah** [comment]
@sslotsky The dependency is internal to Prism. Prism languages have dependencies on other Prism languages.

**Comment by mAAdhaTTah** [comment]
It's not a bug. However you decide to consume Prism, you need to make sure the languages have their dependencies satisfied. Those dependencies are described [here](https://github.com/PrismJS/prism/blob/gh-pages/components.json). You can see [here](https://github.com/PrismJS/prism/blob/gh-pages/components.json#L290-L293) that `handlebars` has a dependency on `markup-templating`.

**Comment by sslotsky** [comment]
I am sorry if I'm being slow, I just _really_ do not understand how this isn't a breaking change. We upgrade a minor version of prism and suddenly our code doesn't work anymore.

**Comment by Golmote** [comment]
Hi.

> This seems like a breaking change for consumers of this library, should there have been a major version bump?

I've took the time to wonder about this since you posted this issue.

Prism provides no insurance that the dependencies between the components won't change. It does provide the insurance that the files [`components.json`](https://github.com/PrismJS/prism/blob/gh-pages/components.json) (and [`components.js`](https://github.com/PrismJS/prism/blob/gh-pages/components.js)) will contain the required information regarding those dependencies.

Furthermore, we usually assume that users using Prism in the browser will get a bundle from the [Download page](http://prismjs.com/download.html). If they were to update to 1.14 using the "redownload URL" on this page, there would be no problem.
The ones who don't can still use the [Autoloader plugin](http://prismjs.com/plugins/autoloader/) if they don't want to handle the dependencies themselves.
Users using Prism with Node are encouraged to use the [`loadLanguages()` helper function](https://github.com/PrismJS/prism/blob/gh-pages/components/index.js), introduced in 1.13, if they want the dependencies to be automatically handled.

For the rest of the users, the ones who decided, on their own, to manually handle those dependencies, yes 1.14 will break their code, regarding the ERB, Handlebars, PHP and Smarty components.

Taking all of this into account, I don't consider 1.14 a BC-breaking release.

I'm really sorry this introduced an issue on Spectacle's side, yet [the way they handle the dependencies](https://github.com/FormidableLabs/spectacle/blob/master/src/utils/prism-import.js) is not really realiable. I don't know their use case, but they should probably have come to us (and maybe they still should) so we could discuss to find a better solution.

**Comment by sslotsky** [comment]
Thank you @Golmote for the thorough explanation.

**Comment by mAAdhaTTah** [comment]
@sslotsky I might suggest opening an issue on Spectacle's repo to open a line of communication about this issue. We don't really have a good "story" for bundlers right now besides that kind of manual setup, so maybe this is a good opportunity to try and solve that.

**Comment by ryan-roemer** [comment]
Hi @Golmote!

If you're still up for it, we're game chatting out a reliable solution for getting a subset of prism deps for Spectacle that we need. Maybe best bet is head over to https://github.com/FormidableLabs/spectacle/issues/546 since it looks like the issue is our method of importing?

For hopefully a useful background, we target CJS + ESM individual files with Babel, and UMD with Webpack.

Thanks!

**Comment by Golmote** [comment]
@ryan-roemer Hi, thanks for getting in touch. I'll join the discussion in FormidableLabs/spectacle#546.

**Comment by Fi1osof** [comment]
Still have error (v 1.22.0). And do not understand how to fix. Can anybody tell like 'just install this dep:...'?
Thanks!
