### ISSUE TITLE
Javascript syntax highlighting for template string nesting doesn't work

### ISSUE THREAD

**Issue by ChrisBrownie55** [PrismJS/prism#1397]
Nesting within a template string does not work correctly, it portrays the first backtick as ending the outside template string and the second one as starting a new template string, for example:

`` Prism.highlight('`${`a string`}`', Prism.languages.javascript, 'javascript') ``

This should produce the following:

```html
<pre>
  <code id="ncode">
    <span class="token template-string">
      <span class="token string">`</span>
      <span class="token interpolation">
        <span class="token interpolation-punctuation punctuation">${</span>
        <span class="token template-string">
          <span class="token string">`a string`</span>
        </span>
        <span class="token interpolation-punctuation punctuation">}</span>
      </span>
      <span class="token string">`</span>
    </span>
  </code>
</pre>
```

But instead it produces this:
```html
<pre>
  <code id="code">
    <span class="token template-string">
      <span class="token string">`${`</span>
    </span>
      a string
    <span class="token template-string">
      <span class="token string">`}`</span>
    </span>
  </code>
</pre>
```

**Comment by Golmote** [comment]
Hi! Thanks for reporting.

Because regexps in JavaScript are not recursive, there is no way for Prism to handle infinite levels of nesting. Yet, we can probably allow for one level of nesting in this special case.

**Comment by ChrisBrownie55** [comment]
@Golmote, there may not be a way to do this with the built-in functions in Javascript, however, it is possible to include a function that makes that possible, however, I do understand that adding in another function that handles recursive regexp just for this would probably be a bit much but I think it would be plausible to add an extension for recursive matching for Javascript in case someone needed it (like me).

**Comment by Golmote** [comment]
@ChrisBrownie55 The issue here is not handling the recursiveness of whatever is inside the template string (this should theoretically work), but rather simply matching the "outer" template string. AFAIK this is not doable with any regexp in JS and it would require a parsing function (that consumes characters until it knows for sure the template string token is fully matched). At the moment, this is not something we want to add to Prism, because of its complexity. See also related https://github.com/PrismJS/prism/issues/1306#issuecomment-368333382.
