### ISSUE TITLE
Too greedy comment highlighting for bash

### ISSUE THREAD

**Issue by Rychu-Pawel** [PrismJS/prism#1457]
I think there is an issue with comment highliting for bash scripts. Please take a look at example on my page: http://pawelrychlicki.pl/Article/Details/58/zfs-health-check-script-for-monit-09

In my opinion lines 57-59, 74-81, 89-93 and 111-131 shouldn't be green. Script is OK as it executes fine. If I put the script into Prism's test drive it looks the same.

**Comment by Golmote** [comment]
Hi! Thanks for reporting. I think this is a problem with the `variable` pattern, not the `comment` one. But there's definitely something wrong starting around line 55.

Would #1443 help there?

**Comment by Rychu-Pawel** [comment]
Nope, didn't help. I replaced bash plugin content with the one from prism-bash.js from mentioned PR but highlighting looks exactly the same :(
I created fiddle for it, with bash algorithm from the PR, here: https://jsfiddle.net/c7ak1p82/1/

**Comment by alice-mm** [comment]
I tried to apply a regexp by @Golmote in my PR and it seems to make things better. If you cannot wait for this to be merged or improved or whatever, I guess you can replace

```
a=$(complicated stuff)
```

with

```
function foo {
    complicated stuff
}

a=$(foo)
```

This should prevent Prism from interpreting the parentheses in your strings as the end of the command substitution, and I think it's a good practice anyway when it comes to scripting as it adds semantics and stuff. Furthermore, even some heavy editors have trouble correctly highlighting complicated command substitution, whereas functions are generally perfectly fine.

By the way, I don't really understand why this issue's title mentions comments since it seems it's the command substitution that is incorrectly parsed.

**Comment by Rychu-Pawel** [comment]
Nice work @alice-mm. I can confirm that changes from your current PR fixes my issue. I'll wait for it to get merged. Thanks!

**Comment by alice-mm** [comment]
You're welcome, @Rychu-Pawel. Also, `grep -E '(foo|bar|plop)'` is equivalent to `grep -E 'foo|bar|plop'`, so you should be able to remove these problematic parentheses (from the `(DEGRADED|FAULTED|…` part) altogether:

```
$ seq 100 | grep -E '56|97'
56
97
```

(`egrep` has been deprecated for years, hence the `grep -E` in these examples.)

**Comment by RunDevelopment** [comment]
Resolved by #1443.

**Comment by rmccullagh** [comment]
So is this change pushed to NPM? How do I get this change?

**Comment by RunDevelopment** [comment]
@rmccullagh A new Prism version will be published on npm soon. 
In the meantime, you can always get the very latest version of Prism at the [download page](https://prismjs.com/download.html).
