### ISSUE TITLE
Importing all languages in vuejs

### ISSUE THREAD

**Issue by mohammad425** [PrismJS/prism#1581]
I install Prism with npm: `npm install prismjs` and import in project:

```
import Prism from 'prismjs'
import 'prismjs/themes/prism-tomorrow.css'


const app = new Vue({
    el: "#app",
    router,
    components: {
        MainApp,
        Prism
    }
});
```

but dont work all languages, like **php**. just work default prism languages.

[screenshot](https://i.stack.imgur.com/TJGkw.png)

**Comment by mAAdhaTTah** [comment]
In the docs, under ["Basic Usage"](https://prismjs.com/#basic-usage) see "Usage with Webpack, Browserify, & Other Bundlers". Let me know if any of that is unclear so we can improve the documentation.

Closing, but feel free to ask follow-up questions.

**Comment by 949mac** [comment]
I know this is old, but here's a link which helped me with my Vue implementation:

https://github.com/search?utf8=%E2%9C%93&q=import+Prism+from+%27prismjs%27+extension%3Avue&type=Code&ref=advsearch&l=&l=

**Comment by ArminCoder** [comment]
In Vue you need to import the languages seperately, for example: import 
```
import 'prismjs/components/prism-python;
import 'prismjs/components/prism-javascript;
import 'prismjs/components/prism-java;
```

**Comment by RunDevelopment** [comment]
@ArminCoder Please __do not__ import languages separately! 

Prism components can depend on each other and that will influence which components you have to import and in which order. Please do handle these dependencies manually. Dependencies between languages are an implementation detail and may change at any time, breaking your code in the process. 
(The only reason your code snippet works in the first place is because the `c-like` component (required by all three) is included when you do `import Prism from "prismjs"`.)

If you have to use static imports, please use our [babel plugin](https://github.com/mAAdhaTTah/babel-plugin-prismjs). 
You simply [tell it what languages you need](https://github.com/mAAdhaTTah/babel-plugin-prismjs#configuring-the-plugin), and the plugin will generate all imports for you, so you don't have to worry about language dependencies.
