### ISSUE TITLE
line numbers overlap with code

### ISSUE THREAD

**Issue by amikrop** [PrismJS/prism#1604]
When using the line-numbers plugin, the line numbers (apart from the first line) overlap with the code, as shown in the screenshot. I also include some of the HTML source.
[code.txt](https://github.com/PrismJS/prism/files/2550421/code.txt)
![screenshot from 2018-11-05 21-49-40](https://user-images.githubusercontent.com/24046/48023866-a6132400-e147-11e8-991d-9b4ec69c8cc9.png)

**Comment by RunDevelopment** [comment]
This bug seems to be cause by the spaces between the opening `pre` and `code` tags.

```html
<pre class="line-numbers">
    <code class="language-python">from __future__ import unicode_literals
```

Prism does not expect that there are any characters between the `pre` and `code` tags.
Simply removing these spaces will solve the problem.

---

One small correction: The first line also overlaps with the list of line numbers; it's just that the first line is also indented with 4 spaces, so it looks right but really isn't.

**Comment by amikrop** [comment]
Thanks!
