### ISSUE TITLE
python language issues

### ISSUE THREAD

**Issue by ncassetta** [PrismJS/prism#1616]
In Python language definition I found some inconsistencies:

"and", "not", "or" are treated as operators in Prism, but IDLE and WING101 (I don't know PyCharm) highlight them as keywords (I agree they should be operators, but this is the usage ...).
The definition seems to reflect Python2: "print" is treated as a keyword (in Python3 it is a builtin function) and "raw_input" (no more used in Python3) is highlighted.  Perhaps Python2 and Python3 should have different definitions.
Thanks for your attention
N. Cassetta

**Comment by ncassetta** [comment]
The only annoying thing should be `print`, which is a command in Python2 and a builtin function in Python3

    # Python 2
    s = 'mum'
    print 'I love', s

and

    # Python 3
    s = 'mum'
    print('I love', s)

In Prism `print` gets the same color of `while`, `for` etc, while (in Python 3) it should have the same of `len` `abs` etc.

**Comment by RunDevelopment** [comment]
You could use the [Highlight Keywords](https://prismjs.com/plugins/highlight-keywords/) plugin to change the style of `print` depending on the Python version.

**Comment by ncassetta** [comment]
Ok, thanks!
I have not tried all the plugins yet!

**Comment by RunDevelopment** [comment]
I'm closing this now because without knowing the Python version of the code, it is impossible to when `print` is not a function.

Example:

```py
print('foo')
```

It's impossible to tell from syntax alone whether it's Python 2 or 3.

---

As I state before:
You can change the highlighting of the `print` keyword specifically using the [Highlight Keywords](https://prismjs.com/plugins/highlight-keywords/) plugin and a bit of CSS.
