### ISSUE TITLE
Issues when building with WebPack

### ISSUE THREAD

**Issue by fabiospampinato** [PrismJS/prism#1724]
The following require call is too dynamic for WebPack: 

https://github.com/PrismJS/prism/blob/00f4f04f0b8ec0357e615767e8dea2cc5c6f75ae/components/index.js#L61

If I'm understanding this correctly that load function is intended to be used from node only. But just making the require call a bit more specific, like so:

```js
require('./prism-' + language)
```

Should solve the issues with WebPack, is there any reason not to solve them?

**Comment by mAAdhaTTah** [comment]
It won't help because that dynamic call will cause Webpack to bundle every language definition and every plugin, which is not what you want. We recommend using `babel-plugin-prismjs` with Webpack.

**Comment by fabiospampinato** [comment]
> which is not what you want

Isn't it? I want all plugins and language definitions to be available to me when I load them.

> We recommend using `babel-plugin-prismjs` with Webpack

I don't think that's what I want, I want everything to be available to me in case I need it, why would I want to narrow down the list of languages manually or list them all maunally?

**Comment by fabiospampinato** [comment]
Keep in mind that a WebPack bundle is not necessarily meant for the web. I'm using WebPack to bundle my Electron app, the few extra kilobytes getting included in the bundle do not matter for me.

Right now I'm using [this function](https://github.com/notable/notable/blob/10e4402fec5bc40f6a50a68833f32c00422b6623/src/renderer/utils/highlighter.ts#L33-L48) for loading languages, which is basically a reimplementation of the included one, minus support for peer dependencies, which I'm not sure what their purpose is.

I don't understand, why would it be bad to make prismjs work with webpack and then suggesting to use the babel plugin as a further optimization rather than forcing to use the babel plugin?

**Comment by mAAdhaTTah** [comment]
The `components.js` also maniulates the cache and some other things that are node-specific, and I think would add all the plugins as well. Additionally, we already have issues with people using the components.js with webpack and ending up with a lot more things bundled than they expect. Saying "you should use components.js w/ node + the babel plugin with webpack" is a lot easier than saying "you can use components.js with webpack and node, but only if you want everything, otherwise, use the babel plugin."

We could add an option to the babel plugin to add everything, like `"languages": "all"` or something of that nature, which could solve the problem. If that interests you, please open an issue over there so we can triage (I haven't worked on that plugin in a bit, but shouldn't be hard to add).

**Comment by fabiospampinato** [comment]
> Saying "you should use components.js w/ node + the babel plugin with webpack" is a lot easier than saying "you can use components.js with webpack and node, but only if you want everything, otherwise, use the babel plugin."

I can't really say the former sounds a lot easier than the latter to be honest, if anything the latter seems a bit clearer to me actually.

> and I think would add all the plugins as well

I'm using prism with webpack and I'm not seeing any extra plugins or languages getting loaded, but they are available to me if I need them.

> We could add an option to the babel plugin to add everything, like `"languages": "all"` or something of that nature, which could solve the problem.

IMHO this is the wrong solution, I shouldn't have to use a babel transformer just for things to work. Like: there isn't a babel transformer for loading all of lodash, because that doesn't make sense, there's instead a babel [transformer](https://github.com/lodash/babel-plugin-lodash) for loading _some_ of lodash.
