### ISSUE TITLE
<pre> line breaks get deleted when calling prism.highlightElement(code)

### ISSUE THREAD

**Issue by SetTrend** [PrismJS/prism#1764]
I set up my HTML using the following snippet:

```html
<div>
 <pre><code class=" language-js" contenteditable="true"></code></pre>
</div>
```

When I call `prism.highlightElement(code);` from the following TypeScript snippet:

```ts
import * as prism from "prismjs";

const code: HTMLElement = document.getElementsByTagName("code")[0];

prism.highlightElement(code);
```

... all line breaks in the `<code>` element get deleted when calling `prism.highlightElement(code)`.
<br/>

### before

![multiple lines](https://user-images.githubusercontent.com/9283914/53380173-c40dca00-396c-11e9-9170-303de94268ea.png)

### after

![one liner](https://user-images.githubusercontent.com/9283914/53380178-c839e780-396c-11e9-88c6-a11e9cf93732.png)
<br/>

#### I believe this is not supposed to happen?
<br/>

**Comment by RunDevelopment** [comment]
I assume that you wrote the highlighted code yourself (because of `contenteditable="true"`).

The problem here is that Prism uses a literal string line break (so `\n` or `\r\n`).
But that is not what the browser will insert when you press <kbd>Enter</kbd>. It will insert a new `<br>` which Prism will ignore (just like all other HTML elements).

The best solution in that is to use keyboard event to handle <kbd>Enter</kbd> yourself.
A working example of this [dabblet](http://dabblet.com/). The script responsible for this behavior can be found [here](https://github.com/LeaVerou/dabblet/blob/master/code/editor.js).

> I believe this is not supposed to happen?

If my assumption is correct, this is supposed to happen.
Otherwise, please provide the full example producing the bug.

**Comment by SetTrend** [comment]
> It will insert a new `<br>` which Prism will ignore (just like all other HTML elements).

Nope. The `<code>` element lies within a `<pre>` element, so `\r\n` and `\n` are both interpreted as newlines by the browser. I debugged my session and I can confirm that `\n` characters are being inserted.

I will upload a sample in short time.

**Comment by SetTrend** [comment]
Is there a public CDN available for Prism I can link to in my sample page?

**Comment by RunDevelopment** [comment]
https://cdnjs.com/libraries/prism will work I guess.

**Comment by RunDevelopment** [comment]
Prism will also add the `language-js` CSS class to the `<pre>` element.
Could it be that this changes the `white-space` property to something which is not `pre`, `pre-line`, or `pre-wrap`?

> I will upload a sample in short time.

Thank you.

**Comment by SetTrend** [comment]
Nope. Checked.

**Comment by SetTrend** [comment]
I created a test page now (the following ZIP file contains the HTML file):

[PrismJS Test.zip](https://github.com/PrismJS/prism/files/2905243/PrismJS.Test.zip)

You were right: The browser adds `<br>` tags instead of using `\n`.

So I needed to replace every occurrence of `<br>` with `\n`:

```js
let code = document.getElementsByTagName("code")[0];

code.innerHTML = code.innerHTML.replace(/[<]br[/]?[>]/gi,"\n");

Prism.highlightElement(code);
```
It was the reason you suggested. Thanks!
<hr/>

Though, AFAICS, the reason is based on the fact that `prism.js` uses [`var code = element.textContent;`](/PrismJS/prism/blob/b5041cf9eaae6f4aefd918f0ef6e0e67ba7ee5bb/prism.js#L211). If Prism would use `element.innerText` instead, the `<br>` would be converted to `\n` by the browser itself, automatically:

![debugger 0](https://user-images.githubusercontent.com/9283914/53411822-d9fca880-39c7-11e9-8cc1-cfb34f93068a.png)

![debugger 1](https://user-images.githubusercontent.com/9283914/53411673-6b1f4f80-39c7-11e9-977f-975f679f7396.png)

![debugger 2](https://user-images.githubusercontent.com/9283914/53411691-812d1000-39c7-11e9-81e8-6beba12f4961.png)

#### Wouldn't it make sense to update the code line in prism.js accordingly?

**Comment by RunDevelopment** [comment]
`innerText` has [a few other properties](https://kellegous.com/j/2013/02/27/innertext-vs-textcontent/) which make it less useful for Prism.
It would also change the current behavior of Prism, so for some people out there, this might be a breaking change.

Also, you can use hooks to make Prism use `innerText`.

```js
Prism.hooks.add('before-sanity-check', function (env) {
    env.code = env.element.innerText;
});
```

**Comment by SetTrend** [comment]
From the description you mentioned I can only read the inteded behaviour and a performance issue.

In contrast to the documents' statement, `innerText` has become a standard meanwhile:

**Comment by RunDevelopment** [comment]
> From the description you mentioned I can only read the inteded behaviour and a performance issue.

Performance aside: Is __breaking change__ not enough reason?

Also, I don't think that it's a good idea for the text Prism highlights to change depending on whether the element is being rendered or not.

What do you think @mAAdhaTTah ?

**Comment by SetTrend** [comment]
Please pardon me for being ignorant. Would you mind elaborating on the issues you see?

I'm just trying to being constructive.

I tested three different scenarios now:

1. `<pre><code>` `</code></pre>`, as suggested by Prism documentation.
1. `<code></code>`
1. `<pre></pre>`

From my perspective I don't see any negative consequences when applying #1766. On the contrary.

`<pre>` is supposed to retain newline characters, so it doesn't make sense to remove them (in the original code, see merge request).

**Comment by RunDevelopment** [comment]
> `<pre>` is supposed to retain newline characters

It does but only _characters_.

> From my perspective I don't see any negative consequences

My main problem is that `textContent` and `innerText` behave slightly differently. Most users of Prism probably wouldn't even notice the change because the `<code>` element Prism highlights isn't supposed to contain markup*.
(* except [when it does](https://prismjs.com/plugins/keep-markup/))

> Would you mind elaborating on the issues you see?

`innerText` is intended to return the text the user gets when selecting and copying the visible text of an element.
So it makes sense that this is what _you_ want. You're writing a text editor, so it makes sense that Prism should highlight what the user sees.

My problem is that this not how Prism behaves now. Prism doesn't highlight the text the user sees, but the text which is there (sounds dumb, I know...).
As an example: `innerText` doesn't return the text of elements which have `display: none`, because they are not visible. Now, how should Prism behave?
I say `display: none` shouldn't matter because markup is stripped. 
Btw.: Same problem for `display: block` where extra `\n`s will be inserted around the block.

Now, the next problem: `innerText` is only really defined for elements which are visible. As a consequence, its behavior changes depending on whether the element, from which you want the `innerText`, is visible.
Example: Let's say we highlight a `code` element. With `innerText` we might get _different_ results depending on whether the element is visible (_right now_) or not. (Happy debugging...)

(Well and then again: Most users don't care, so why not do them a favor and use what's faster.)

Summary:
My main issue is that the behavior of Prism changes. So we risk breaking the code of a lot of Prism users.
Also, there is this more general question of how Prism __should__ behave. Should it highlight the visible text or all text?

---

Again: I can see why you want to use `innerText` in your specific use case but you don't need to change all of  Prism for that. [You can use the features Prism already provides to implement this](https://github.com/PrismJS/prism/issues/1764#issuecomment-467421570).

**Comment by SetTrend** [comment]
I'm not sure whether these edge cases really matter. However, of course, I refrain from my pull request.

Just to finish the discussion, regardless of the result:

* I wouldn't expect nodes deliberately designated to be `display: none` to still appear. I personally would consider this behaviour unexpected, or even not desired, if I happened to stumble over it.

* I would expect nodes deliberately designated to be `display: block` to be displayed with line-breaks. Otherwise I wouldn't expect the web page designer to have applied that attribute to those nodes in the first place.

* A few minutes ago I applied `display: none` to the `<code style="display: none">` element. The result: `innerText` was the same as `textContent`: Both omit child elements when the element is hidden.

  I comprehend that old (pre-standard) IE implementations behave differently. For these edge cases `element.innerText || element.textContent` should have sufficed.
<br/>

I would have considered the `innerText` behaviour - including its line-break behaviour - much more what I'd expect from the converted result as the `textContent` behaviour.

**Comment by SetTrend** [comment]
The hook appears to be incorrect. The correct hook name is: `before-highlight`

```js
Prism.hooks.add('before-highlight', function (env)
{
  env.code = env.element.innerText;
});
```

**Comment by RunDevelopment** [comment]
> The hook appears to be incorrect. The correct hook name is: `before-highlight`

I specifically wanted [`before-sanity-check`](https://github.com/PrismJS/prism/blob/master/components/prism-core.js#L227) because it is executed before (almost) all other hooks and (more importantely) before the checks of `highlightElement`.

**Comment by regularlabs** [comment]
This works too:
```
Prism.hooks.add('before-sanity-check', function (env)
{
  env.element.innerHTML = env.element.innerHTML.replace(/<br>/g, '\n');
  env.code = env.element.textContent;
});
```

**Comment by FunMiles** [comment]
This has been closed for a while, but I am having a problem as well with straight code like this:
```js
import Prism from 'prismjs';
let thecode = "int main()\n{\n  3+4;\n}";
html = Prism.highlight(thecode, Prism.languages.clike);
```

The resulting html has no line break despite the 3 `\n` in the source code.
```html
int <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
  <span class="token number">3</span><span class="token operator">+</span><span class="token number">4</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
```

What am I doing wrong?

**Comment by RunDevelopment** [comment]
> The resulting html has no line break despite the 3 `\n` in the source code.

Prism's HTML output is intended for `pre` elements which use [`white-space: pre`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) by default. Set this property for the element you're using for displaying code, and everything should work fine.

**Comment by FunMiles** [comment]
> > The resulting html has no line break despite the 3 `\n` in the source code.
> 
> Prism's HTML output is intended for `pre` elements which use [`white-space: pre`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) by default. Set this property for the element you're using for displaying code, and everything should work fine.

I am not using an element and do not wish to use an element. I have markdown text downloaded from a server and want to use svelte to put the HTML in an element afterwards using svelte's `{@html html}`. Can't I call the `highlight` function so that it does treat it as if it got the text from a `pre` element? I've only looked over the code for `hilightElement` and it does get the text in what seems should result in the same code I am passing to `highlight`, but I am not seeing yet how its call of `highlight` is differently from what I do.

I am sure you can help me with that 👍

**Comment by fricaro** [comment]
> The hook appears to be incorrect. The correct hook name is: `before-highlight`
> 
> ```js
> Prism.hooks.add('before-highlight', function (env)
> {
>   env.code = env.element.innerText;
> });
> ```

I had this issue trying to add Prism.js to Anki card template and I fixed it by adding this hook to Prism.js code. Thank you!

**Comment by Tey** [comment]
Another workaround is to prevent the browser from adding the "\<br>" element this way:
```js
pre.addEventListener("keydown", function (e) {
  if (e.key === "Enter") {
    e.preventDefault();

    const sel = window.getSelection();
    const range = sel.getRangeAt(0);

    const textNode = document.createTextNode("\n");
    range.insertNode(textNode);

    // Move caret after the inserted newline
    range.setStartAfter(textNode);
    range.setEndAfter(textNode);
    sel.removeAllRanges();
    sel.addRange(range);
  }
});
```
This does not rely on innerText and does not require an extra read of the full content before highlighting.
