### ISSUE TITLE
Falcon Lang Support

### ISSUE THREAD

**Issue by qfish** [PrismJS/prism#1884]
**Falcon**
Falcon is a  is a powerful language for describing your structured data. It is easy for developer to read and write.

**Additional resources**
https://marketplace.visualstudio.com/items?itemName=FalconTeam.falcon

**Comment by RunDevelopment** [comment]
Could you please also post a link to the language's website, specification, or project?

**Comment by RunDevelopment** [comment]
I will now close this. There has never been a response to my request for a language specification/documentation. There is a [falcon language](http://www.falconpl.org/) but it very different from what was presented in #1885. I searched for quite a while but the only other thing from "FalconTeam" I could find was the VSCode extension. This VSCode extension is the only proof that I could find that this Falcon language even exists.

Since I have no idea what language we are supposed to add support for, I will now close this.
