### ISSUE TITLE
JavaScript string quote punctuation highlighting

### ISSUE THREAD

**Issue by atomiks** [PrismJS/prism#1912]
The current pattern used is:

```regex
/(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/
```

This includes the quotes (`"'`) in the scope. What can be used instead to exclude them, so that they are instead part of the `punctuation` scope?

**Comment by RunDevelopment** [comment]
Instead of excluding the quotes you can add them as inside punctuation like so:

```js
{
    pattern: /(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,
    greedy: true,
    inside: {
        'punctuation': /^["']|["']$/
    }
}
```

This is the standard Prism way to highlight code inside tokens.

If excluding the quotes was your only option however, then it can be done like this:
(You will also need to adjust the `punctuation` pattern of course.)

```js
{
    pattern: /(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*(?=\1)/,
    lookbehind: true,
    greedy: true
}
```
