### ISSUE TITLE
Add CDN configurator to homepage

### ISSUE THREAD

**Issue by foxycode** [PrismJS/prism#1922]
**Motivation**
When I hit https://prismjs.com/download.html there is nice configurator for files to download. It would be nice to also show all files I need to include if I want to use CDN. I tool me really long time to find that I need also `prism-markup-templating.js` too to whole thing to work.

**Description**
I'd like to have a list of CDN files I need to include as a second option to download configured source from https://prismjs.com/download.html

**Comment by RunDevelopment** [comment]
I don't think that we need this.

IMO the end user shouldn't have to worry about which files have to be loaded in what order so that syntax highlighting for e.g. TypeScript or PHP (since you mentioned `markup-templating`) works. Not only is this annoying but it's also error-prone because languages have quite a few dependencies on each other which not only determine what has to be loaded but also in which order.

Another downside of loading languages and their dependencies ourselves is that we usually load languages by declaring `script` tags like this:

```html
<!-- I just want to highlight PHP and TypeScript code -->
<script src="https://myCDN.com/prism/components/prism-core.js"></script>
<script src="https://myCDN.com/prism/components/prism-markup.js"></script>
<script src="https://myCDN.com/prism/components/prism-markup-templating.js"></script>
<script src="https://myCDN.com/prism/components/prism-php.js"></script>
<script src="https://myCDN.com/prism/components/prism-clike.js"></script>
<script src="https://myCDN.com/prism/components/prism-javascript.js"></script>
<script src="https://myCDN.com/prism/components/prism-typescript.js"></script>
```

All of them are loaded sequentially one after another when a few of these could be loaded in parallel.

__The solution__

The [Autoloader plugin](https://prismjs.com/plugins/autoloader/) can do all of this language loading and dependency handling for you.

The above code then becomes:

```html
<!-- I just want to highlight PHP and TypeScript code -->
<script src="https://myCDN.com/prism/components/prism-core.js"></script>
<script src="https://myCDN.com/prism/plugins/autoloader/prism-autoloader.js"></script>
<script>Prism.plugins.autoloader.languages_path = 'https://myCDN.com/prism/components/'</script>
```

Please note that the Autoloader loads languages asynchronously as needed, so won't ever load languages, you don't have to. 
But this also means that only the languages you have already used are loaded, so keep that in mind if you use the Prism API more directly.

I hope that the Autoloader works for you. If not, then we can reopen this.

**Comment by foxycode** [comment]
@RunDevelopment I tried your example, but no I see only plain text and no error in Chrome console.

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.16.0/prism.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.16.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script>Prism.plugins.autoloader.languages_path = 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.16.0/components/'</script>
```

Am I doing something wrong?

**Comment by RunDevelopment** [comment]
@foxycode 
Your code works perfectly well on my side.

I will need a bit more context to help you. Could you set up a [JSFiddle](https://jsfiddle.net/) (or similar) that reproduces your issue?

<details>
<summary>A minimal example</summary>

```html
<html>
<head> <!-- title, CSS, and stuff --> </head>
<body>

<pre><code class="language-java">public class Abc {

	public void doesItWork() {
		System.out.println("Yes, it does!");
	}

}</code></pre>

<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.16.0/prism.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.16.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script>Prism.plugins.autoloader.languages_path = 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.16.0/components/'</script>
</body>
</html>
```

</details>

**Comment by foxycode** [comment]
@RunDevelopment Unfortunately, your example isn't working for me either.

In Chromium: <a href="http://i.imgur.com/w2Xj2VK.png">
  <img src="http://imgur.com/w2Xj2VKl.png" />
</a>

In Firefox: <a href="http://i.imgur.com/2my79Rd.png">
  <img src="http://imgur.com/2my79Rdl.png" />
</a>

Isn't working on JSFiddle either: <a href="http://i.imgur.com/iTbD5wn.png">
  <img src="http://imgur.com/iTbD5wnl.png" />
</a>

JSFiddle link: https://jsfiddle.net/k48rxbLe/
Browsers (both on Ubuntu Linux):
* Chromium 74.0.3729.169 (Official Build) snap (64-bit)
* Firefox Quantum 67.0 (64-bit)

**Comment by RunDevelopment** [comment]
@foxycode The example _is_ working. It's just that I didn't include a theme, so you can't see the tokenize text.

[Here](https://jsfiddle.net/80c3qpsd/1/)'s a version with the default theme plus a PHP example.

**Comment by foxycode** [comment]
@RunDevelopment Aaaaand it's working for me now too :)

That is why I wanted at least some example of using CDN on your homepage. I believe there is none ;)

**Comment by RunDevelopment** [comment]
That's true. I'll add one.
