### ISSUE TITLE
Line numbers on server side

### ISSUE THREAD

**Issue by lcswillems** [PrismJS/prism#1945]
Hi,

I would like to know if it is possible to add the line numbers on server side?

Here is my code:

```
import Prism from 'prismjs';
import 'prismjs/plugins/line-numbers/prism-line-numbers';

Prism.highlight(mycode, Prism.languages.javascript);
```

**Comment by RunDevelopment** [comment]
No, because line numbers are added after the actual highlighting using DOM manipulation. `Prism.highlight` returns a string, so no DOM manipulation possible.

But, you could use a virtual DOM and `Prism.highlightElement` to add line numbers (I haven't actually done that yet, so I can't guarantee that it works). The problem here is that you won't get the [resize event](https://github.com/PrismJS/prism/blob/f571cfce19c7a13df375a2fd921b64e16fa6e71e/plugins/line-numbers/prism-line-numbers.js#L65) on the client, so you can't get soft wrap if it works at all.

**Comment by lcswillems** [comment]
Okay, thank you for this fast answer :)
