### ISSUE TITLE
Make it possible to have two definitions result in the same style class.

### ISSUE THREAD

**Issue by david-nossebro** [PrismJS/prism#1995]
I have a use case where I am extending a language and would like to add additional keywords to the original definition.
The only way I found to do this is either to merge the original regexp with the new one or create a separate definition and give it the same style. 
It would be nice if it would be possible to give the same style-class to multiple definitions somehow. 

As an example, if I add keywords as below I would loose the original 'keyword' definition and only get the two added keywords highlighted.
```javascript
Prism.languages.extend("c", {
   keyword: /(one_more|another_one)/
});
```
One way is to do it like this:
```javascript
Prism.languages.extend("c", {
   new_keyword: /(one_more|another_one)/
});
```
And then append the same style to the 'new_keyword' class in css.

Another way is to include the two new words together with the original regexp from the repository. But that becomes long and ugly, and if the original definition changes we will not get the updated. 

I propose something like this:
```javascript
Prism.languages.extend("c", {
   new_keyword: {
      definition: /(one_more|another_one)/,
      styleClass: 'keyword'
   }
});
```

**Comment by mAAdhaTTah** [comment]
I think you're looking for `alias`: https://github.com/PrismJS/prism/blob/master/components/prism-javascript.js#L36

**Comment by RunDevelopment** [comment]
There are multiple ways to solve your problem.

As @mAAdhaTTah pointed out, you can add a new token and use an alias.

```js
Prism.languages.extend("c", {
    'new_keyword': {
        pattern: /(one_more|another_one)/,
        alias: 'keyword'
    }
});
```

This appends the new token `new_keyword` at the end of the grammar. All words matched by it will have the following CSS class name: `.token.new_keyword.keyword`.

Another way is to use token arrays.

```js
Prism.languages.extend("c", {
    'keyword': [
        Prism.languages.c.keyword,
        /(one_more|another_one)/
    ]
});
```

Here, we replace the old C definition of `keyword` with an array containing both the C `keyword` and your pattern so both patterns will have the `keyword` class.
One pitfall here is that `Prism.languages.c.keyword` can't be an array because nested arrays aren't supported.

For more information on both methods, see the [extending page](https://prismjs.com/extending.html#language-definitions).

**Comment by david-nossebro** [comment]
Thanks for your response, I did not know it was possible! :)
