### ISSUE TITLE
prism-shell.js is missing

### ISSUE THREAD

**Issue by weiqi7777** [PrismJS/prism#2022]
**Information:**
- Prism version: [e.g. 1.14, latest from the download page, etc.]
laster
- Environment: [e.g. Browser, Node, Webpack]
gitbook
Does the latest version of Prism from the [download page](https://prismjs.com/download.html) also have this issue?
yes
If you're using Prism with Node or Webpack, please also see the [usage section](https://prismjs.com/index.html#basic-usage).

**Description**
A clear and concise description of what the bug is and how to reproduce it.

hi, i use gitbook with prism plugin. 
when i write shell code with markdown. 
```shell
egt -f rtl.vf
```
use below command to generate html:
   gitbook serve
and ,I get below error:
{ Error: Cannot find module 'prismjs/components/prism-shell.js'

  i look the dir prismjs/components dir, and find prism-shell-session.js and prism-shell-session.min.js, but not prism-shell.js.
 
  i copy prism-shell-session.js to prism-shell.js, and modify the prism-shell.js file, rerun the comand :  gitbook serve   
   the error is missing.

**Example**
An example which reproduces the bug. This can be a link to a website, a [JSFiddle](https://jsfiddle.net/), an attached example project, etc.

can you have a look?
thanks
jun.lu

**Comment by RunDevelopment** [comment]
What you are looking for is the Bash language definition. Bash actually has the [`shell` alias](https://github.com/PrismJS/prism/blob/9f7225864143369ef7f092f657d148318a7a151c/components.json#L140), so Gitbook should be able to load Bash. 
That it tries to load `prism-shell.js` shows that they did not implement an alias resolver.

This is not a bug of Prism but of Gitbook.
Please [report](https://docs.gitbook.com/faq) this to the Gitbook team.

In the meantime, you could use `bash` instead of `shell`.

**Comment by weiqi7777** [comment]
very thanks.
it's my fault.
