### ISSUE TITLE
New language on the fly

### ISSUE THREAD

**Issue by Opsse** [PrismJS/prism#2043]
**Motivation**
I want to add a new language for [a very specific case](https://github.com/irakoton/language-deepsec).   
I found [this documentation](https://prismjs.com/extending.html#creating-a-new-language-definition), but according to it I need to add it directly to Prism source code and rebuild everything. Which seems totally overkill for my needs.

**Description**
I'm looking for a way to define a new language on the fly. Is it currently possible?

**Comment by RunDevelopment** [comment]
Yes, it's possible.

The documentation is written the way it is because some plugins (Autoloader, Show Language) require a language to be registered in `components.json` and need a rebuild. So if you want to use these plugins, there's no way around a rebuild.

If you just want Prism to highlight some code and don't care about plugins, you can add the language yourself like this:

```js
Prism.languages['my-language'] = {
    'token': /pattern/,
    ...morePatterns
};
```

That's all Prism needs to highlight code with your grammar.

BUT, Prism won't be able to load your language definition, so you have to do that yourself.

Browser:
```html
<script src="prism.js"></script>
<script src="my-language.js"></script>
<!-- or inline it -->
<script>
Prism.languages['my-language'] = { ... };
</script>
```

Node:
```js
const Prism = require('prismjs');

require('./my-language');
// or
Prism.languages['my-language'] = { ... }
```

**Comment by Opsse** [comment]
This looks perfect, I will try, thank you for the detailed answer.

In my opinion it could be useful to add this on the documentation.
