### ISSUE TITLE
High CPU load on code hovering

### ISSUE THREAD

**Issue by voed** [PrismJS/prism#2120]
**Information:**
- Prism version: latest from the download page
- Plugins: none
- Environment: Chrome Beta  79.0.3945.45 Windows

One CPU core loads to 100% and scrolling is freezed when i'm hovering code block. Bug exists even on download page.
![image](https://user-images.githubusercontent.com/10352360/69459910-7dbe8d80-0d7b-11ea-95ce-332debe15f05.png)

**Comment by RunDevelopment** [comment]
Thanks to a recent change in Chrome's layout engine, hit tests can take a looooong time. Up to several seconds long depending on the length of the highlighted code and the current machine.

Since it's a chrome-only issue, we decided that this is something Chrome has to fix.
See #2062 for more info (also includes a hacky workaround).
