### ISSUE TITLE
[Question] How to code recursive language definition?

### ISSUE THREAD

**Issue by Opsse** [PrismJS/prism#2133]
I defined my language this way :

```
let filters = {
  position: {
    pattern: /%\d+(-\d+)*%[^%]+%/ // Something like "%142%...%" or "%752-1-2%...%"
  },
  comment: /\/\/.*$/,
  keyword: {
    pattern: /(?<=\b)(new|let|if|then|else|in)(?=\s|%)|(?<=\s|%)->(?=\s|%)|(?<=^|\s|;|%)!~\d+/,
    inside: {
      sup: /~\d+/
    }
  },
  'in-out': /(?<=\b)(in|out|eavesdrop)(?=\()/,
  operator: /=\|\+/,
  function: {
    pattern: /(?<=^|[\s,;()%])(#?\w+|proj_{\d+,\d+})(?=\()/,
    inside: {
      sub: /(?<=\w)_\d+(?=\b)/
    }
  },
  'no-args': /\(\)/,
  punctuation: /[(),;]/u,
  sup: /(?<=\w)~\d+(-\d+)*(?=\s|$|_|%)/,
  sub: /(?<=\w)_\d+(?=\b|~|%)/,
}

// Recursive definition for position
filters.position.inside = filters

// Define the language grammar
Prism.languages.deepsec = filters
```

The `position` tag is recursive and create the following stack overflow error : 

> RangeError: Maximum call stack size exceeded

But the documentation say : 

> However, keep in mind that they’re slower and if coded poorly, can even result in infinite recursion.

So how can I correctly define my language to deal with this recursive definition?

**Comment by RunDevelopment** [comment]
The problem here is that your `position` pattern will always match causing infinite matches. To illustrate the iterations:

Let's assume we have the text: `%123%foo% // bar`

1. The `position` pattern will match the string `%123%foo%`. Because `position` has an `inside` property, we do recursive matching. The inside is the `filters` object.
2. The input string is `%123%foo%` (the string matched by the `position` pattern). The `position` pattern will match the whole string. Because `position` has an `inside` property, we do recursive matching. The inside is the `filters` object.
    I hope that it's obvious that step 2 will be repeated indefinitely because the `position` can always match a string it matched before.

There are 2 solutions to this problem:
1. __Consume at least one character__ before you use the same grammar again in a recursive manner.
2. Use __lookarounds__ so that the pattern cannot match a its own match.

In your example, this might look like this:
1.  ```js
    let filters = {
        'position': {
            pattern: /%\d+(-\d+)*%[^%]+%/, // Something like "%142%...%" or "%752-1-2%...%"
            inside: {
                'deepsec': {
                    pattern: /%[^%]+%$/, // this will only match the last "%...%" part
                    inside: null // will be set to filters
                },
                ...otherTokens
            }
        },
        ...other
    };
    ```
2.  ```js
    let filters = {
        'position': {
            pattern: /(?!^)%\d+(-\d+)*%[^%]+%(?!$)/, // can't be the first token
            inside: null // will be set to filters
        },
        ...other
    };
    ```
    (I don't know the language, so I couldn't come up with a better example...)

I hope this helps.

**Comment by Opsse** [comment]
That makes sense, thank you for the details.
