### ISSUE TITLE
question: script variations; defer and async?

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#2149]
Could someone provide a little more explanation of what the `prism.js` script does and where we may place it?

The [official instructions](https://prismjs.com/#basic-usage) say to load it at the end of the document using `<script src="prism.js"></script>`. But most modern browsers now seem to support `async` and `defer` when used in `<head>`, according to [an answer on Stack Overflow](https://stackoverflow.com/a/24070373/421049). According to [one explanation with diagrams](https://flaviocopes.com/javascript-async-defer/), we should be able to load the script in `<head>` and just use `defer` to have it load asynchronously yet execute after the document.

**Comment by RunDevelopment** [comment]
You can generally place Prism's `<script>`s anywhere you like. If Prism detects that the page is currently loading, it will delay the highlighting until the DOM is ready, so it doesn't really matter _when_ Prism is loaded/its script is executed. The highlighting itself is done via the `Prism.highlightAll` method.

The only restriction to your total freedom is plugins/languages in separate files. In that case, you'll have to use `defer` or the no-attribute version of both `<script>`s because with multiple files, order matters.

But if you only have one Prism file, then you _should_ be able to place this anywhere you like and in any way you like, I _think_. (I can't think of a configuration which doesn't work at least.)

**Comment by garretwilson** [comment]
So just to confirm: without a normal single Prism.js script inclusion, I don't even need to use `defer`? I can just include the script in `<head>` and it will work fine?

**Comment by garretwilson** [comment]
Sorry to repeat the question; you were pretty clear in your answer. I was just wanted to be double-sure.

I dropped the `defer` and it seems to work in `<head>` so far. Thanks so much for the response.

**Comment by mAAdhaTTah** [comment]
> I don't even need to use `defer`?

You may want to use `defer` for performance reasons, but that depends on the particulars of your setup. Leaving out `defer` means it pauses while the script is downloaded and executed. Adding it allows the browser to continue parsing & rendering and delay the script execution until that process has completed.

It's worth testing that on your site to see what's fastest for you, but Prism should function correctly in all scenarios, **as long as all Prism scripts have the same attributes**, e.g. if you have Prism core + the autoloader, either both or neither should use `defer`.

**Comment by garretwilson** [comment]
> Leaving out `defer` means it pauses while the script is downloaded and executed. Adding it allows the browser to continue parsing & rendering and delay the script execution until that process has completed.

Ah, thanks for reminding me. I knew that when I wrote the question, but with all the hustle and bustle since I wrote that it slipped my mind. I'll add `defer` back in.
