### ISSUE TITLE
Shell-session doesn't get highlighted

### ISSUE THREAD

**Issue by Magicrafter13** [PrismJS/prism#2173]
**Information**
- Language: shell-session
- Plugins: Line Highlight, File Highlight, Show Language, Highlight Keywords, Remove initial line feed, Inline color, Keep Markup, Command Line, Normalize Whitespace, Toolbar, Copy to Clipboard Button, Download Button, Match braces, Diff Highlight

Using latest version of Prism

**Description**
I am unable to get anything with language-shell-session to highlight on my site OR the PrismJS "Test drive" page (https://prismjs.com/test.html#language=shell-session).

![image](https://user-images.githubusercontent.com/29127566/72193140-f83f7d00-33bc-11ea-9f05-8f10b18367b7.png)

**Code snippet**

<details>
<summary>Page snippet</summary>

```
<pre class="command-line shell-session" data-user="matthew" data-host="matthew-p7-1500z" data-filter-output="out ">
  <code>
scp &lt;path_to_your_local_file&gt; &lt;username&gt;@[private]:~
out Debian GNU/Linux 8
out (your file)                                          100%   (file size)   (average transfer speed)   (total time elapsed)
  </code>
</pre>
```

</details>

![image](https://user-images.githubusercontent.com/29127566/72193319-ba8f2400-33bd-11ea-9f1d-f8d6fd70f04e.png)

The only page where I've seen it appear to work is the examples page (https://prismjs.com/examples.html)
![image](https://user-images.githubusercontent.com/29127566/72193348-deeb0080-33bd-11ea-8be3-977a7d09187e.png)

**Comment by RunDevelopment** [comment]
Shell session is not intended to be used with the [Command Line plugin](https://prismjs.com/plugins/command-line/). The shell session language is supposed to be a simple replacement for the Command line plugin for the case that Prism plugins aren't supported in your environment or you don't want to use the Command line plugin.

Shell session will identify commands by the `$` prefix and interpret everything else as the output of commands. This is useful when writing shell tutorials but it's also the reason why you didn't see any highlighting.

Command line, on the other hand, doesn't make any assumptions. You have to explicitly tell it which lines are command and which are output. From your snippet, I can see that you already did that correctly.

Now, with the background info out of the way, let's fix your snippet. There are two problems:
1. You're using the wrong language. Use `shell` instead of shell session.
2. You're not using the `language-xxxx` class format to declare the language. Prism won't detect the language unless it's declared like this.

<details>

This should work.

```html
<pre class="command-line language-shell" data-user="matthew" data-host="matthew-p7-1500z" data-filter-output="out ">
  <code>
scp &lt;path_to_your_local_file&gt; &lt;username&gt;@[private]:~
out Debian GNU/Linux 8
out (your file)                                          100%   (file size)   (average transfer speed)   (total time elapsed)
  </code>
</pre>
```

</details>

I hope this solves your issue.
