### ISSUE TITLE
Cannot read property 'children' of null

### ISSUE THREAD

**Issue by bkdotcom** [PrismJS/prism#2192]
**Information:**
- Prism version: 1.19.0
- Plugins: https://prismjs.com/download.html#themes=prism&languages=markup+css+clike+javascript+json+markup-templating+php+php-extras+sql&plugins=line-highlight+line-numbers 
- Environment: Chrome 79

**Description**
Error thrown in console 
```
Uncaught TypeError: Cannot read property 'children' of null`
 at Object.getLine
```

**Example**
I'll attempt to create one... I can't tell what's triggering this issue

**Comment by RunDevelopment** [comment]
From the error logged, I see that [this line](https://github.com/PrismJS/prism/blob/0bf73dc7813cdd1eadb15730d8c9f2d00f208df8/plugins/line-numbers/prism-line-numbers.js#L164) is the problem but the function `getLine` itself isn't being used by Line Numbers, so Line Highlight is [the cause of the problem](https://github.com/PrismJS/prism/blob/0bf73dc7813cdd1eadb15730d8c9f2d00f208df8/plugins/line-highlight/prism-line-highlight.js#L81). (I assume that you don't call the function `getLine` manually.)

But that's about as much as I can help you with the information you provided. The problem is that the Line Highlight plugin seems to be executed before the Line Numbers plugin, which means that Line Highlight will try to the line numbers of a code block that don't yet exist.

Is that really the full stack trace of the error?

**Comment by RunDevelopment** [comment]
Cannot reproduce + no further information provided

**Comment by bkdotcom** [comment]
Looks to be triggered via resizing the window

**Comment by RunDevelopment** [comment]
No, there isn't a template. You can also upload a .zip file with a little project. Anything that reproduces the issue is fine.

---

> unrelated...

Will fix.

**Comment by bkdotcom** [comment]
@RunDevelopment 

sorry for the delay..  I've just been living with the console errors.. 
upgraded to 1.22... still see the issue, so tracked down the cause

### I'm using the manual option...
`Prism.manual = true;`

line number plugin is listening for window resize

	window.addEventListener('resize', function () {
		var actions = $$('pre[data-line]').map(function (pre) {
			return highlightLines(pre);
		});
		actions.forEach(callFunction);
	});

which appears to try to iterate over all `pre[data-line]`..  assuming prism has already rendered the output..  in order to re-render the line numbers...

but it can't re-render what hasn't been rendered to begin with

```
var lineNumberRows = element.querySelector('.line-numbers-rows');  // null if not yet rendered
...
// Uncaught TypeError: Cannot read property 'children' of null
var lineNumberEnd = lineNumberStart + (lineNumberRows.children.length - 1);   
```
### it needs to filter / only re-render that which has been rendered

**Comment by RunDevelopment** [comment]
Thank you for the detailed explanation! I'll make a fix.

**Comment by bkdotcom** [comment]
Awesome!
Thanks
