### ISSUE TITLE
Prism JS with Dev Extreme Text Area

### ISSUE THREAD

**Issue by ttaylor29** [PrismJS/prism#2234]
Hello,

Is it possible to use prism .js with SQL lanageuage on a dev extereme text area control?

Or is prism.js only available on static content?

**Comment by RunDevelopment** [comment]
AFAIK, it's not possible to highlight anything inside a regular `<textarea>` element because it simply display its text content ignoring any HTML tags inside of it. Since all styling will be ignored, you cannot highlight code inside a `<textarea>` element.
I don't know what a " dev extereme text area control" but as long as it is a plain old `<textarea>` element, it is generally not possible (that [hasn't stopped some people](https://codepen.io/aktorou/pen/YWxorK) thou).

However, if it's not  a `<textarea>` (or `<input>`), then it can be done. Prism is a general syntax highlighter, so you can give it some text and a language and it will highlight the text returning HTML source code for the highlighted text.

Example:

```js
const htmlSource = Prism.highlight(myCode, Prism.languages.sql, 'sql');
someElement.innerHTML = htmlSource;
```

(To actually see any highlighting, you still need a theme.)

[More details of Prism's API](https://prismjs.com/extending.html#api).

**Comment by ttaylor29** [comment]
Hello,

Dev extreme text area control is this: https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTextArea/

Thanks for the information!  We will look at something else.
