### ISSUE TITLE
diff-highlight and language-diff-${language} rendering issue on Safari

### ISSUE THREAD

**Issue by jaapbakker88** [PrismJS/prism#2238]
**Information**
- Language: all that I tested, Kotlin, Java, Dart, JS, Swift, Diff
- Plugins: diff-highlight

**Description**
On Safari, when using diff and the diff-highlight plugin, Span's are rendered to the the codeblock and the code dissapears. You can see this happen on the plugin page on the prism website. https://prismjs.com/plugins/diff-highlight/

![image](https://user-images.githubusercontent.com/1172870/75664130-43199a80-5c72-11ea-8ff0-990fe38b35f6.png)

**Comment by tbarbugli** [comment]
After doing some debugging it looks like the problem is related to how the `HTML_LINE` regex is generated. Replacing the generated regex with hardcoded version fixes the problem.

**Comment by RunDevelopment** [comment]
The page works in Chrome, Firefox, Edge, and IE11, so this is definitely a safari-specific bug.

Thank you @tbarbugli for doing the debugging.
This is just a guess, but are could it be that `\r` and `\n` aren't escaped properly in the `.source` property? If not, what's the difference between the generated and hard-coded pattern?

**Comment by tbarbugli** [comment]
@RunDevelopment that was my first guess as well but that's not it. Here's the two version of the `HTML_LINE` patterns:

Chrome

```
(?:<\/?(?!\d)[^\s>\/=$<%]+(?:\s(?:\s*[^\s>\/=]+(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s'">=]+(?=[\s>]))|(?=[\s/>])))+)?\s*\/?>|[^\r\n<])*(?:\r\n?|\n|(?:<\/?(?!\d)[^\s>\/=$<%]+(?:\s(?:\s*[^\s>\/=]+(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s'">=]+(?=[\s>]))|(?=[\s/>])))+)?\s*\/?>|[^\r\n<])(?![^\r\n]))
```

Safari

```
(?:$<%]+(?:\s(?:\s*[^\s>\/=]+(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s'">=]+(?=[\s>]))|(?=[\s/>])))+)?\s*\/?>|[^\r\n<])*(?:\r\n?|\n|(?:$<%]+(?:\s(?:\s*[^\s>\/=]+(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s'">=]+(?=[\s>]))|(?=[\s/>])))+)?\s*\/?>|[^\r\n<])(?![^\r\n]))
```

For some reason I don't know, Chrome generates a different (correct) pattern than Safari. 

Not sure what is the advantage of having the `HTML_LINE` regex to be computed at runtime, if not needed I would say having the final regex hard-coded is the easy fix.

**Comment by tbarbugli** [comment]
https://github.com/PrismJS/prism/pull/2239

**Comment by RunDevelopment** [comment]
For some reason, the first 18 characters of the pattern are simply gone! It's a miracle the pattern doesn't throw a syntax error. I simply cannot believe that Safari is unable to execute the following lines of code correctly.

```js
var HTML_TAG = /<\/?(?!\d)[^\s>\/=$<%]+(?:\s(?:\s*[^\s>\/=]+(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s'">=]+(?=[\s>]))|(?=[\s/>])))+)?\s*\/?>/gi;
var HTML_LINE = RegExp(/(?:__|[^\r\n<])*(?:\r\n?|\n|(?:__|[^\r\n<])(?![^\r\n]))/.source.replace(/__/g, HTML_TAG.source), 'gi');
```

The interesting part now is: Where does it go wrong? Is it the `.source` stored incorrectly or is the `String.prototype.replace` at fault?
If I were to guess, then I'd say that Safari is having trouble with the `$<%` part of the pattern. My guess is that it is somehow interpreting this as a substitution. If my suspicion is correct, then messing with the substitution sequence should fix it. I guess `[^$\s>\/=<%]` instead of `[^\s>\/=$<%]` will work? Could you please test this @tbarbugli? (I'd like to do the debugging myself, but I don't have access to a macOS computer.)

Either way, this problem is huge because a few of Prism's languages also generate patterns in a similar fashion meaning that all those languages will potentially not work in Safari.

> Not sure what is the advantage of having the HTML_LINE regex to be computed at runtime

Redundancy. If hard-coded, the `HTML_TAG` pattern will be present at 3 different locations in the file. It also makes the pattern easier to understand (because you don't have to mentally parse a 280 characters long regex).

**Comment by Golmote** [comment]
`$<` seems to be used for named captures (https://tc39.es/ecma262/#table-45) and Safari's behaviour seems to be per spec to be honest: it searches for a named capture called `%]+(?:\s(?:\s*[^\s` and since it can't find it, it replaces with the empty string. There must be a subtlety that I don't get, though, if it work properly in Chrome.

Changing this order of the characters in the character class should indeed work. A safer but uglier alternative would be to use `HTML_TAG.source.replace(/\$/g, '$$$$')` as the replacement string, I guess.
