### ISSUE TITLE
Is it possible to use 'keep-markup' and 'unescaped-markup' together?

### ISSUE THREAD

**Issue by sheriffderek** [PrismJS/prism#2240]
**Motivation**
I think that marking specific parts of the code is helpful for teaching. I've enjoyed using 'keep-markup' for JavaScript - but now I'd like to use it for templates as well - and I don't want to escape those templates. I'm comparing and contrasting HTML, PHP, JS, Vue, Ember - so I'd like to have control for writing those templates - and being able to pick out highlights with a custom CMS or by hand.

**Description**
I would like to write markup without manually escaping the usual suspects (so, using unescaped-markup plugin) - and also make visual highlights in the code manually with _mark_ (so, using keep-markup plugin) - but they don't seem to work well together.

![Screen Shot 2020-03-03 at 11 35 13 PM](https://user-images.githubusercontent.com/2066617/75855948-2da68c80-5da8-11ea-9bee-0ac9c4d5af53.png)

![Screen Shot 2020-03-03 at 11 32 39 PM](https://user-images.githubusercontent.com/2066617/75855970-3bf4a880-5da8-11ea-82ea-3de98f93b25f.png)

I'll gladly pay someone to help me make this happen. : )

**Alternatives**
I've written out some basic version by hand - and used prism for it too. Here's an early attempt:  https://codepen.io/sheriffderek/pen/NAYbJX from years ago - - and here is an example I just made to help outline the question: https://codepen.io/sheriffderek/pen/510fb2379addf64f5d89a239487df393?editors=1000

![Screen Shot 2020-03-03 at 11 45 25 PM](https://user-images.githubusercontent.com/2066617/75856402-22079580-5da9-11ea-8344-e7f423f3a617.png)

(also - I can make another report - but the comment version of the unescaped-markup doesn't seem to be working in this example)

![Screen Shot 2020-03-03 at 11 46 46 PM](https://user-images.githubusercontent.com/2066617/75856467-45324500-5da9-11ea-9f04-b04b97738338.png)

**Comment by Golmote** [comment]
Hello ! I don't really understand how that could be a thing. We can't both interpret your markup to restore it after highlighting (keep-markup) and escape it to display it uninterpreted (unescaped-markup)...

How would you mark parts of an HTML snippet for example?

**Comment by sheriffderek** [comment]
Yeah. @Golmote - I see what you mean. I was trying to wrap my head around it. I don't have any practical experience building something like this. I used some all too 'happy-path' examples when I was testing it - so, I just thought "Oh! it works!" But I see the conflict. Do you have any suggestions? Is what I'm trying to accomplish clear?

**Comment by Golmote** [comment]
Yeah, I believe I understand what you're trying to achieve but I can't think of a generic way of doing so.

The first idea that comes to my mind would be to be able to mark parts of the code using configurable "marking" tags I suppose, so that it can be adapted to the wild variety of languages supported by Prism. But it still feels hacky and not easy to use. And you'll still need a way to escape those when you don't want them to be interpreted...

I truly feel like the best solution would be for you to implement a way to automatically escape your code snippets so that you can mark them using the keep-markup plugin and stop relying on the unescape-markup plugin.

(Also the issue you mentioned regarding using the comment version of the unescape-markup plugin seems to be related to Codepen. It works properly on the [plugin page on the prism website](https://prismjs.com/plugins/unescaped-markup/).)

**Comment by sheriffderek** [comment]
OK! Thanks for taking a look. I think you can close this with a "No" - this isn't possible because the two things conflict. I'll try and think up a way to do it - or just create some bitmap images for my purposes.

_RE: other issue: good catch!_
