### ISSUE TITLE
String Interpolation {{ myText }} in not working in Prism

### ISSUE THREAD

**Issue by ziagit** [PrismJS/prism#2241]
Hi there,
I'm using Prism with Laravel, 
The problem I face; when I have something like {{myText}} in my HTML file, this string interpolation cause, not to show the whole page,  

I have added languages; like html, css, javascript, typescript, php...
and plugins, I just added line highlight. 
could you please help, if I'm missing any language to add or plugin

thanks

**Comment by RunDevelopment** [comment]
@ziagit Please provide an example that reproduces the issue and the language (`.language-xxxx`) you use to highlight that example.

**Comment by ziagit** [comment]
thank you RunDevelopment for replying me
in bellow code
`<table>
      <tr>
        <th>File name</th>
        <th>Actions</th>
      </tr>
      <tr v-for="file of files">
      
        **<td>file</td>**
        <td>
          <form v-on:submit.prevent="downloadFile(file)">
            <md-button class="md-raised md-danger" type="submit">Download</md-button>
          </form>

          <form v-on:submit.prevent="deleteFile(file)">
            <md-button class="md-raised md-danger" type="submit">Delete</md-button>
          </form>
        </td>
      </tr>
    </table>`

when I choose Html when I add the code

**Comment by RunDevelopment** [comment]
I'm sorry @ziagit but I still don't understand your issue. If I highlight your code on [our test page](https://prismjs.com/test.html#language=markup), I was not able to see any problems.

And I don't understand what you mean by _"in the above example, `{{title}}` causes a blank page"_. I don't see how Prism can cause a blank page because Prism just highlights code and nothing else*. 
(* Plugins give Prism some extra features but they don't do much.)

**Comment by Cosnavel** [comment]
@RunDevelopment I think I got the point of @ziagit

**Comment by RunDevelopment** [comment]
I opened #2403 for this.
