### ISSUE TITLE
Scheme lonely numbers

### ISSUE THREAD

**Issue by jcubic** [PrismJS/prism#2367]
This works fine:

```scheme
(10)
```
but this not:

```scheme
10
```

It seems that GitHub do the same.

**Comment by RunDevelopment** [comment]
We could change the lookbehind of [`number`](https://github.com/PrismJS/prism/blob/0d65d6c9b712c827ad417c4558bdc28b5ac8a555/components/prism-scheme.js#L44) from this `([\s()])` to this `(^|[\s()])`, so it also accepts the start of a string. However, because of the way Prism works, `^` might also match the end of the previous tokens. This _might_ lead to a lot of false positives.

I'll take a look at it and how it affects actual Scheme code.
