### ISSUE TITLE
Include `.sol` for Solidity 

### ISSUE THREAD

**Issue by viarnes** [PrismJS/prism#2381]
**Information**
- Language: Solidity
- Plugins: none, but I'm ssing Prism through Vuepress

**Description**
Solidity syntax highlighting works perfect when specifying it with the `solidity` keyword. However, it doesn't work when importing a `*.sol` file.

**Code snippet**

```
<<< @MyContract.sol
```

**Comment by RunDevelopment** [comment]
First: This an issue you should have opened [here](https://github.com/vuejs/vuepress). The [snippet feature is currently in beta](https://v1.vuepress.vuejs.org/guide/markdown.html#import-code-snippets), so this is valuable feedback.

That being said, I looked at the code and [this](https://github.com/vuejs/vuepress/blob/54b84b3a780785488c6a6f309f84dd720b872d51/packages/%40vuepress/markdown/lib/snippet.js#L134-L148) is where it goes wrong. 
It assumes that Prism has an alias for every file extension (we usually do but not always). This is not a good solution as heavily relies on Prism's aliases and doesn't account for the fact that different languages sometimes use the same file extension (e.g. OpenCL code and Common Lisp both use `.cl`). There should be a way for the user (that's you! ^^) to specify the language of a file.

For now, I'll make a PR to add the `sol` alias because it seems reasonable. This __will not__ solve your issue because right now because [VuePress' Markdown uses our npm package](https://github.com/vuejs/vuepress/blob/54b84b3a780785488c6a6f309f84dd720b872d51/packages/%40vuepress/markdown/package.json#L31) and we don't plan to release a new version in the next few days.

To solve your issue, open an issue on the [VuePress Github page](https://github.com/vuejs/vuepress). This is an issue of VuePress, not Prism.
If you really need this to be solved in a timely manner, you could probably make a PR to VuePress. A simple extension mapping approach should fix you problem for now (not ideal but simple). This is also what [Prism's File Highlight plugin](https://github.com/PrismJS/prism/blob/master/plugins/file-highlight/prism-file-highlight.js#L12) does (the extension map hasn't been updated for a while tho).
