### ISSUE TITLE
Release 1.21.0?

### ISSUE THREAD

**Issue by cmcaine** [PrismJS/prism#2398]
If master is stable, could we get a quick release?

Thanks so much for maintaining and developing this project ❤️

**Comment by RunDevelopment** [comment]
master is always stable. 

The Prism [download page](https://prismjs.com/download.html) gets its files directly from master (that's why master has to be stable), so you can get new features for there (if that's applicable to you).

We will probably make a new release for npm at the end of the month or a few days later.
(If you need it right now, you can tell npm to fetch Prism directly from master.)

**Comment by cmcaine** [comment]
Great :)
