### ISSUE TITLE
React JS Guide or Documentation

### ISSUE THREAD

**Issue by rgvillanueva28** [PrismJS/prism#2399]
**Motivation**
I am implementing PrismJS on my React JS App but I can't find a good guide in using plugins and other languages. I manually import all the languages and plugins I am using and I even have an error when importing the toolbar and the cpp language. However, it works on other languages

**Description**
Here is my .babelrc file
![image](https://user-images.githubusercontent.com/45262256/82724022-8c273b00-9d05-11ea-82e5-20f78d38dcb2.png)

Here is the code snippets of my imports
![image](https://user-images.githubusercontent.com/45262256/82724070-f63fe000-9d05-11ea-9703-3d095d752207.png)

**Alternatives**
Are there any guides or documentations which supports React JS?

**Comment by RunDevelopment** [comment]
If you use the Babel plugin, shouldn't `import Prism from 'prismjs';` be enough?

---

@mAAdhaTTah

**Comment by mAAdhaTTah** [comment]
Yes and if you make `css: true` in your babel config, you won't need to import `prism-line-number.css` either.

That said, for React in particular, couple of options:

1. Use something like `react-prism-renderer`: https://github.com/FormidableLabs/prism-react-renderer Or another project that wraps React around Prism.
2. Use a Ref to grab the node you want to highlight & highlight it yourself with `Prism.highlightElement`. With this approach, you probably want to to enable manual highlighting with `Prism.manual = true`.

Happy to answer any followup questions, but going to close because this isn't an issue.

**Comment by rgvillanueva28** [comment]
It's working as expected now.

I was trying it yesterday and restarted the app several times but no luck. Today, I don't know why it's working.

Case closed. Thanks!!!

**Comment by rgvillanueva28** [comment]
Hi. It's not working again. I'm not sure but I think it has to do with the .babelrc file.
Should I be reporting at the babel-plugin-prismjs repository instead?

**Comment by RunDevelopment** [comment]
@mAAdhaTTah

**Comment by mAAdhaTTah** [comment]
Because you don't have a dependency array in useEffect, it runs the highlighting on every render. That might be your issue. If not, please provide an isolated, runnable example of your issue.

**Comment by rgvillanueva28** [comment]
Here is an example:
[https://repl.it/repls/ImprobableFeistySymbols#src/App.js](https://repl.it/repls/ImprobableFeistySymbols#src/App.js)

**Comment by mAAdhaTTah** [comment]
@rgvillanueva28 The example is using CRA, so you don't actually have control over babel, so the prismjs plugin isn't actually injected, which means the language you're expecting to be there isn't, despite the babel plugin being configured correctly. You'll need to eject from CRA, or we'd have to explore providing a macro for this use case.

**Comment by rgvillanueva28** [comment]
I see. That's why it's working on my other project because i ejected it. Thanks for the Answer. Appreciate it.
