### ISSUE TITLE
Class to escape keep markup on certain code elements

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#2433]
I love Keep Markup, but it's interacting badly with a dynamic code snippet. It would be nice to be able to escape it on a case by case basis, in the same way one can escape whitespace normalization.

Perhaps a `drop-markup` or `dont-keep-markup` class?

**Comment by RunDevelopment** [comment]
Why don't we implement a general opt-in/opt-out mechanism for plugins (where applicable)? 
A class `plugin-name` will be used to activate a plugin for a given code block and a `no-plugin-name` can be used to deactivate it. Both classes are inherited, so you can de/activate a plugin for many code elements at once. 
(Regarding the opt-out-class: `no-` works kinda well for all plugins but `dont-` works really well if followed by a verb, so why not have both?)

We can implement this as a little `Prism.util` function that, given a code element, the plugin name, and whether the plugin is active by default, will return whether the plugin is activated. Plugins can then juts call that function instead of each having their own logic for opt-in and opt-out.

We already have an opt-out for Normalize whitespace (not inherited) and opt-in for Line numbers (inherited). I feel like now is a good time to add a general mechanism.

**Comment by LeaVerou** [comment]
Love the idea! Does that mean we can remove that logic from normalize whitespace?

**Comment by RunDevelopment** [comment]
Yes! (See #2434.)
