### ISSUE TITLE
TOML lang line breaks on section

### ISSUE THREAD

**Issue by MattixNow** [PrismJS/prism#2443]
**Information**
- Language: `TOML`
- Plugins: `none`

**Description**
Prism create punctuation element for `[[section]]` in toml

**Code snippet**

App.js
```jsx
import React from "react";
import Prism from "prismjs";
import "prismjs/components/prism-toml";

const App = () => {
  return (
    <PrismCode language="toml">
      {`[[redirects]]
  from = ""
  to = ""
  status = 301`.trim()}
    </PrismCode>
  );
};

```

```jsx
export default class PrismCode extends React.Component {
  constructor(props) {
    super(props)
    this.ref = React.createRef()
  }
  componentDidMount() {
    this.highlight()
  }
  componentDidUpdate() {
    this.highlight()
  }
  highlight = () => {
    if (this.ref && this.ref.current) {
      Prism.highlightElement(this.ref.current)
    }
  }
  render() {
    const { children, plugins, language } = this.props
    console.log(children);
    
    return (
      <pre className={!plugins ? "" : plugins.join(" ")}>
        <code ref={this.ref} className={`language-${language}`}>
          {children}
        </code>
      </pre>
    )
  }
}


```

it render :
![image](https://user-images.githubusercontent.com/32040951/86040227-f38e8400-ba43-11ea-9760-f4c89e18b5a8.png)

**Comment by RunDevelopment** [comment]
The [test page](https://prismjs.com/test.html#language=toml) renders everything as expected.

![image](https://user-images.githubusercontent.com/20878432/86048969-9994bb00-ba51-11ea-91c3-af2280d57bd0.png)

The bug lies somewhere in your code, but unfortunately, I don't know enough about React to tell you what it is.

**Comment by MattixNow** [comment]
ok

**Comment by gomorizsolt** [comment]
@MatteoGauthier Did you happen to sort this issue out? I'm also facing with it.

**Comment by RunDevelopment** [comment]
Looking at the issue again, my best guess is that `display: block` got applied to `redirects`. The HTML of `redirects` is `<span class="token table class-name">redirects</span>` and you probably have a `.table` rule (or similar) in your stylesheets.

**Comment by gomorizsolt** [comment]
Thanks @RunDevelopment for the guess. Indeed, there were additional styles applied to `redirect`. In my case, Tailwind CSS was the culprit because when you use the [`@tailwind utilities`](https://tailwindcss.com/docs/functions-and-directives#tailwind) directive it injects a `.table` class whose `display` property is set to `table` (hence the line breaks because `table` is a block-level element).

In order to get around this "style glitch", I simply overrode the `display` property with `initial`:

```css
@layer utilities {
  .table {
    display: initial;
  }
}
```
