### ISSUE TITLE
Lack of formatting for java & python within Gatsby

### ISSUE THREAD

**Issue by GarciaPL** [PrismJS/prism#2448]
**Information**
- Language: JS, Python, Java
- Plugins: none
- Prism: 1.20.0

**Description**
I am trying to onboard PrismJS for Gatsby. I do not want to use plugin called gatsby-remark-prismjs as I am trying to make some custom work. I have component which formats JS, but it does not of Java & Python.

Do I need to load anything more apart of prismjs from npm ?

**Code snippet**

```
import React from "react";
import Prism from "prismjs";

export default class PrismCode extends React.Component {
  constructor(props) {
    super(props);
    this.ref = React.createRef();
  }
  componentDidMount() {
    this.highlight();
  }
  componentDidUpdate() {
    this.highlight();
  }
  highlight = () => {
    if (this.ref && this.ref.current) {
      Prism.highlightElement(this.ref.current);
    }
  };
  render() {
    const { code, plugins, language } = this.props;
    return (
      <div>
        <pre className={!plugins ? "" : plugins.join(" ")}>
          <code ref={this.ref} className={`language-${language}`}>
            {code.trim()}
          </code>
        </pre>
      </div>
    );
  }
}

```

<details>
<summary>The code being highlighted incorrectly.</summary>

```
num_sqrt = num ** 0.5
print('The square root of %0.3f is %0.3f'%(num ,num_sqrt))
```

</details>

**Comment by RunDevelopment** [comment]
Prism is modular by design. The Prism instance you get by importing `from "prismjs"` only includes Markup, CSS, JS, and C-like (a language prototype used to create other languages, e.g. JS).

There are multiple ways to load more languages depending on your environment. If the rendering is purely server-side, you can use the [`loadLanguages`](https://prismjs.com/#basic-usage-node) to dynamically load languages as needed. 
If you're rendering in the browser, it will be harder. If you know the languages you want to support, our [babel plugin](https://github.com/mAAdhaTTah/babel-plugin-prismjs) will be your best bet. If you wanted to dynamically load languages in the browser, [choose a CDN and go with our Autoloader plugin](https://prismjs.com/#basic-usage-cdn). You can use the import `from "prismjs/plugins/autoloader/prism-autoloader"` but then you have to set the [CDN manually](https://prismjs.com/plugins/autoloader/#how-to-use).

(Autoloader page is broken rn. I'll fix it.)

**Comment by RunDevelopment** [comment]
I think, I answered the question and since there hasn't been a response, I'll assume that the issue was solved.

Feel free to reopen if the issue isn't solved yet.
