### ISSUE TITLE
Nothing working except the theme

### ISSUE THREAD

**Issue by SM-Fahim** [PrismJS/prism#2477]
**Information:**
- Prism version: latest from the download page
- Plugins: Quiz and Survey master, QSM advertisement be gone
- Environment: Browser

**Description**
I started using Prismjs a week ago. Downloaded the files from the website. It worked perfectly. But today I noticed that it's no longer working. Changes I've made before noticing the problem are, updated the theme, added plugin, and add-on. Found out that the problem is because I don't use a child theme. So I uploaded the js, css files again and added coded to functions.php. It worked, but not properly. Only the theme work. That means, I chose a dark theme and now my codes are showing the dark theme. But the line numbers, copy option, syntax highlighting are no longer working. 

**What I've tried so far**
Downloaded the css, js files again. Uploaded in the panel, added codes to functions.php. But not working. Downgraded the theme (Divi 4.5.1 to 4.5.0) and repeated everything. Still not working. 

**How I use prismjs**
Just uploaded the css and js files, added some codes to functions.php. Then using Guttenberg, I write my desired codes in _code_ widget. And in the advanced settings of each _code_ widget, I write these codes:
`language-bash`    # for single line code
`language-bash, line-numbers`    # for multi line code

**Code I added in functions.php file**
Tried both alternatively:

```php
function add_prism()
{
    wp_enqueue_style( 'prism-css',  get_stylesheet_directory_uri() . '/prism.css' );
    wp_enqueue_script( 'prism-js',  get_stylesheet_directory_uri() . '/prism.js', [], false, true );
}
add_action( 'wp_enqueue_scripts', 'add_prism' );
```

And,

```php
// Function to add prism.css and prism.js to the site
function add_prism() {
    // Register prism.css file
    wp_register_style(
        'prismCSS', // handle name for the style so we can register, de-register, etc.
        get_stylesheet_directory_uri() . '/prism.css' // location of the prism.css file
    );
    // Register prism.js file
    wp_register_script(
        'prismJS', // handle name for the script so we can register, de-register, etc.
        get_stylesheet_directory_uri() . '/prism.js' // location of the prism.js file
    );
    // Enqueue the registered style and script files
    wp_enqueue_style('prismCSS');
    wp_enqueue_script('prismJS');
}
add_action('wp_enqueue_scripts', 'add_prism');
```

**I'm not using child theme**
As wordpress will be releasing a major update soon, so almost every theme and plugins are releasing updates frequently. That's why I'm not using any child theme.

**Example**
Please see this page on [Bash Scripting](https://www.machinelearningwiki.com/bash/). Please check the last few posts. The codes have dark theme, but no line numbers and copy option.

**Comment by RunDevelopment** [comment]
> The codes have dark theme, but no line numbers and copy option.

Works on my system.

![image](https://user-images.githubusercontent.com/20878432/87547768-dac0d800-c6ab-11ea-9027-6f1836dae089.png)
[source](https://www.machinelearningwiki.com/bash-scripting/printing-something-echo-clear/)

**Comment by SM-Fahim** [comment]
@RunDevelopment 
I just discovered that when I'm logged into my WordPress dashboard, it's not working. But when I log out and reload the page, then it's working. But why is this happening?

**Comment by RunDevelopment** [comment]
You don't see any line numbers but do you see syntax highlighting?

If I had to guess, then WP does some magic while you're logged in. Prism's automatic highlighting works by attaching a call to `Prism.highlightAll` to a [DOM event](https://github.com/PrismJS/prism/blob/bea7a58579c00b7dbf75a572a7e502920e7f814a/components/prism-core.js#L1111). So if WP loads code blocks asynchronously after this event, Prism won't highlight them.

What happens if you open the dev console and call `Prism.highlightAll()` manually after the page finished loading?

**Comment by SM-Fahim** [comment]
![pr](https://user-images.githubusercontent.com/30735259/87554781-60f21400-c6d6-11ea-8a4c-88defc21d344.png)
When I'm logged into WP, this is how it looks.
By dev console, you mean inspect>console? 
If yes, then it's still the same

**Comment by RunDevelopment** [comment]
> By dev console, you mean inspect>console?

Yes.

> It says, undefined.

You mean, `Prism.highlightAll()` returns `undefined`, right? That's expected because the function doesn't return anything.

> it's still the same.

This means that Prism can't find your code blocks. Prism searches for code blocks like this: `document.querySelectorAll("<Prism's code element selector>")`. There could be multiple reasons for this:

1. WP wraps your page in an `iframe`.
1. WP uses the shadow DOM to add your page.
1. WP adds some elements between the `pre` and `code` elements. (How does the tree of the `pre` element in your screenshot look like?)

**Comment by SM-Fahim** [comment]
![prsm1](https://user-images.githubusercontent.com/30735259/87561220-2be9bf80-c6de-11ea-9b5a-474599bf571c.png)
![prsm](https://user-images.githubusercontent.com/30735259/87561233-2f7d4680-c6de-11ea-8de4-1796de410862.png)
Please have a look. Sorry for being annoying, I'm not familiar with html,css,js. (I'm comfortable with other languages)

**Comment by RunDevelopment** [comment]
It's alright. We all have trouble in unfamiliar environments.

---

Not quite enough information but I can rule out number 2.

Two things: First, please send a screenshot like this:
![image](https://user-images.githubusercontent.com/20878432/87563105-2630b180-c6bf-11ea-9b68-edc3e6edceac.png)

I need to be able to see the full (expanded) markup structure of the `pre` element. (Just right-click the code block, click _Inspect_, and expand collapsed nodes (if any) under `pre`.) I also need to be to see the full path of the `pre`. (You might have to [reposition dev tools](https://developers.google.com/web/tools/chrome-devtools/customize/placement) for this.) (The full path the little list of elements, you see at the bottom 
![image](https://user-images.githubusercontent.com/20878432/87564106-4c0a8600-c6c0-11ea-8409-c78f72bf0d49.png).)


Secondly, what is the result of the following? (Just paste it into the dev console.) It should find 10 `code` elements.

```js
document.querySelectorAll("code")
```

**Comment by SM-Fahim** [comment]
I'm trying to follow your instructions. Please have a look:

1. From WP editor page:
![p0](https://user-images.githubusercontent.com/30735259/87566678-2d6ab600-c6e5-11ea-9863-a695bfef47ac.png)

2. From frontend, but logged into WP:
![Uploading p1.png…]()

3. Output from the code:
![p2](https://user-images.githubusercontent.com/30735259/87566814-555a1980-c6e5-11ea-9bf7-f820c036bb61.png)

**Comment by RunDevelopment** [comment]
> From WP editor page:

WP replaces the code block with a `textarea`, so we can't do any highlighting there.

> Output from the code:

It found the code blocks. That's good.

> From frontend, but logged into WP:

That's interesting. We can see that the `code` block has the `.language-bash` class. Since this class is not present on the `code` element in the source code of the page, we know that Prism added the class.

Honestly, this looks like the result of a Prism instance without any plugins and no bash language. Could you please check your Prism instance in the dev console. It should look like this:

![image](https://user-images.githubusercontent.com/20878432/87575340-11104e80-c6d0-11ea-9e86-b97fe47a6e6e.png)

**Comment by SM-Fahim** [comment]
Don't know how but it's working now. I was just modifying my fonts and
other settings and noticed that it's working now.
