### ISSUE TITLE
Question: Can I get grammar from language name

### ISSUE THREAD

**Issue by atodorov** [PrismJS/prism#2517]
I'd like to use Prism as the highlighter for marked (in combination with SimpeMDE preview).  I've got the necessary plumbing working like so:

```javascript
SimpleMDE.prototype.markdown = function(text) {
    var markedOptions = { sanitize: true };

    if(this.options && this.options.renderingConfig && this.options.renderingConfig.codeSyntaxHighlighting === true && window.Prism) {
        markedOptions.highlight = function(code, lang) {
            return window.Prism.highlight(code, window.Prism.languages.python, lang);
        };
    }

    marked.setOptions(markedOptions);

    return marked(text);
}
```

In the `highlight()` function `lang` is the language passed from markdown, e.g. the value after the 3 back-ticks (see the raw version of this comment). 

Can I somehow get the appropriate grammar for the 2nd argument ?

**Comment by RunDevelopment** [comment]
Since the lang used by users is usually the same as Prism language ids, you can just access it directly from `Prism.languages` like so:

```js
Prism.highlight(code, Prism.languages[lang], lang);
```

You can see a full list of all supported language ids [here](https://prismjs.com/#supported-languages). Keep in mind that the third argument has to be one of the language ids of the grammar passed as the second argument.

That being said, you might want to do some form of mapping e.g. from `c++` -> `cpp`. I did a simple mapping like [this](https://github.com/PrismJS/prism/blob/2da2beba24b459cec461a91368ce902b7e276a46/components/prism-markdown.js#L281).

Also, you might be interested to know that our [markdown language can highlight fenced code blocks](https://prismjs.com/plugins/autoloader/#markdown) too. It will even use the [Autoloader](https://prismjs.com/plugins/autoloader/) plugin (if present) to dynamically load the necessary grammars on the fly.
