### ISSUE TITLE
JS Extras doesn't work on Test Drive Page

### ISSUE THREAD

**Issue by karlhorky** [PrismJS/prism#2527]
**Information:**
- Prism version: Version on Test Drive Page
- Plugins: Plugins on Test Drive Page
- Environment: Test Drive Page

**Description**
The `JS Extras` Language doesn't seem to work to highlight JS on the Test Drive page:

<img width="360" alt="Screen Shot 2020-08-26 at 10 49 03" src="https://user-images.githubusercontent.com/1935696/91283121-7a34b880-e78a-11ea-94e2-9e41bcebe0b8.png">

**Example**

https://prismjs.com/test.html#language=js-extras

```js
import v from "mod";
import {x as v2} from "mod";
import * as ns from "mod";

export * as ns from "mod";
export {v as x} from "mod";
export {x} from "mod";
export {v as x};
export {x};
```

**Comment by RunDevelopment** [comment]
This isn't obvious, but JS Extras only modifies JS. It's not a language itself. To use JS Extras in Test Drive, you have to first select JS Extras and then select JavaScript.

**Comment by karlhorky** [comment]
Ah right, I understand.

Would the Prism.js team be open to changing the test page to show these languages which don't work on their own in some separate UI as a one-time loading link or button? Something maybe similar to the following super quick draft mockup?

![Screen Shot 2020-08-27 at 11 44 05](https://user-images.githubusercontent.com/1935696/91424904-b20b3100-e85a-11ea-9157-447c0aee258e.png)

And only show this link or button when a related language is selected?

**Comment by RunDevelopment** [comment]
Hmmm. I'm not sure what to do here.

(From now on, let's call languages _non-grammar languages_ if they only modify other languages and don't export a grammar themselves. All other languages will be called _grammar languages_.)

The main problem is that, right now, each radio button has two functions: 1) it loads the language and all of its (require) dependencies, and 2) it sets the language as the current highlighting language. However, function 2) doesn't make sense for non-grammar languages, so it's confusing.

Your solution is to move all non-grammar languages into their own category. I'm not sure if I like this because we use this exact language list everywhere on the website and then, suddenly, on the test page it's split in two?

How about this: We make it a two-step process.
First, the languages to be loaded are selected, and then the highlighting language is selected from the subset of all loaded grammar languages. 
I imagine a list of checkboxes (similar to the download page) to select which languages are loaded and via another list (the subset) of radio buttons to select the current grammar language. To make the process less annoying, the last grammar language selected in the checkbox list will automatically be used as the current highlighting language.
(Too overengineered?) 

Thoughts?

**Comment by karlhorky** [comment]
> How about this: We make it a two-step process.
> First, the languages to be loaded are selected, and then the highlighting language is selected from the subset of all loaded grammar languages.
> I imagine a list of checkboxes (similar to the download page) to select which languages are loaded and via another list (the subset) of radio buttons to select the current grammar language. To make the process less annoying, the last grammar language selected in the checkbox list will automatically be used as the current highlighting language.
> (Too overengineered?)
> 
> Thoughts?

For a single language set (single grammar language and 0+ non-grammar languages) I think this seems ok:

1. User selects `javascript`
2. User selects `js-extras`
3. (`javascript` automatically selected in grammar list)

However, if a user selects more than one grammar language, the UX starts to get a bit confusing:

1. User selects `javascript`
2. User selects `js-extras`
3. User selects `php`
4. (`php` is automatically selected, and the user can then select between `php` and `javascript` to switch)
5. User wants to switch to `ruby`
6. User then has to select `ruby` at the top
7. (`ruby` is automatically selected in the grammar list below)

Seems like we're making a separate list at the bottom anyway, but it has two confusing UX aspects:

1. It does not have all available languages
2. It may not be clear how to add new languages here

Since this solution is suggesting a separate list anyway, maybe we can take another look at the problem that you mentioned about the list being used everywhere:

> Your solution is to move all non-grammar languages into their own category. I'm not sure if I like this because we use this exact language list everywhere on the website and then, suddenly, on the test page it's split in two?

This is a good point. Maybe this issue is uncovering that there is a separation somehow that could make sense to expose also elsewhere on the website?

For example, let's take the heading on the index page:

![Screen Shot 2020-08-27 at 14 17 09](https://user-images.githubusercontent.com/1935696/91444442-091dff80-e875-11ea-8f45-d0a961485733.png)

If I was a new developer coming to read about this syntax highlighting library, it seems impressive: 231 programming languages, wow!

However, really there are not 231 programming languages - there are a number of non-grammar languages in there.

To me it seems like these non-grammar languages are different enough to list out separately everywhere, potentially under one of these terms suggestions:

1. language modifiers (similar to the `modify` option on the Extending Prism page)
2. language extensions

If a new section like this would be conceivable, which pages would need to be changed? These three?

A. Index
B. Download
C. Test

**Comment by RunDevelopment** [comment]
> It may not be clear how to add new languages here

Everything is automatically generated from `components.json`. This includes all language lists on the website and everything that deals with languages. Changing the code that generates the lists is easy once we know what we want.

> there is a separation somehow that could make sense to expose also elsewhere on the website?

I wonder? The problem is that those categories aren't as clear cut as they might seem. First of all, there are 3 categories: 1) grammar languages, 2) libraries, and 3) extensions. 
Grammar languages are what you usually mean with "programming language" (e.g. C/C++). Libraries contain functions and data to create/modify other languages (e.g. Markup Templating). Extensions modify existing languages (e.g. JS Extras).

Every language fits _at least_ one of those categories. And that's the problem: we have languages that fit into multiple categories which makes categorizing tricky. 
Prime example: Javadoc-like. This language exports a grammar and functions, and it modifies existing languages.
Another example: JS and CSS. Both are extensions for Markup. (And Markup exports a function to modify itself making it partly library...)

I think that we can assign each language a __main category__ (e.g. JS mainly a grammar language). This will give a more accurate language count and help with de-cluttering the download page a little. I'll make an issue for that.

But I don't think that this will help us with the Test drive page, does it?

---

To clarify: I imagined a page like this:
![image](https://user-images.githubusercontent.com/20878432/91455109-fb22ab80-e881-11ea-9f90-93fcdc6a9c11.png)

(JS Extras will be in the list of checkboxes but it won't appear in the list of to select the current language)

**Comment by karlhorky** [comment]
> Everything is automatically generated from `components.json`. This includes all language lists on the website and everything that deals with languages. Changing the code that generates the lists is easy once we know what we want.

Ah, I meant from a user UX perspective - it may be hard to figure out how to "add" a new Current Language to the top, especially if they're new to the website or if they've received a link to the website sent to them by someone else.

> I think that we can assign each language a **main category** (e.g. JS mainly a grammar language)
>
> But I don't think that this will help us with the Test drive page, does it?

I'm thinking it may be one option. Let's say you have these three categories:

1. grammar languages
2. libraries
3. extensions

...and you use them to separate the `<input>`s on the Test Drive page.

Then the "Languages" category (grammar languages) could be radio button inputs and everything else could be checkbox inputs:

```html
<h3>Languages</h3>

<label>
  <input type="radio" /> Markup
</label>

<label>
  <input type="radio" name="language" /> CSS
</label>

<label>
  <input type="radio" name="language" /> JavaScript
</label>

<h3>Language Libraries</h3>

<label>
  <input type="checkbox" /> CSS Extras
</label>

<label>
  <input type="checkbox" /> JS Extras
</label>

<h3>Language Extensions</h3>

<label>
  <input type="checkbox" /> Regex
</label>
```

Actually pretty close to your UI suggestion, but no duplication.
