### ISSUE TITLE
Cannot set property 'keyword' of undefined

### ISSUE THREAD

**Issue by donskov** [PrismJS/prism#2531]
**Information:**
- Prism version: 1.21.0
- Plugins: 'none'
- Environment: Webpack

**Description**
Use `prism-glsl` import and see the error (works in `1.20.0`).

Browser console:

![image](https://user-images.githubusercontent.com/9417251/91463193-c15aa080-e893-11ea-8dab-57475cf92e3a.png)

Browser page (React error):

![image](https://user-images.githubusercontent.com/9417251/91463236-d0415300-e893-11ea-815e-90e3ad6d5127.png)
![image](https://user-images.githubusercontent.com/9417251/91463312-ec44f480-e893-11ea-8849-d2f4448abcdf.png)
![image](https://user-images.githubusercontent.com/9417251/91463334-f2d36c00-e893-11ea-8ac9-c947b08d5c13.png)

**Example**

Some React component:
```jsx
import Prism from 'prismjs';
import 'prismjs/components/prism-glsl';

...
```

**Comment by RunDevelopment** [comment]
That's because GLSL depends on some other languages. 

[Our babel plugin](https://www.npmjs.com/package/babel-plugin-prismjs) can take care of those dependencies for you. `import Prism from 'prismjs'` will then return a Prism instance with all your languages, so you don't need to import any languages yourself.

Hope this helps.

**Comment by donskov** [comment]
@RunDevelopment Thanks for the response. Babel plugin does not suit me, because I don't use babel.

I found a simple solution and it works for me without plugin:

```js
import Prism from 'prismjs';
import 'prismjs/components/prism-c';
import 'prismjs/components/prism-glsl';
...
```
