### ISSUE TITLE
Does plugin implement any encoding?

### ISSUE THREAD

**Issue by CodAffection** [PrismJS/prism#2556]
I'm just curious, is it possible to encode & decode code blocks, so that we can prevent normal HTML rendering from messing with our source code. It was there in my WordPress theme - Avada. The code block will be encoded before saving to DB, It will be decoded once page is fully loaded. Is it possible for our library with or without the help of an external framework?

**Comment by mAAdhaTTah** [comment]
I'm not sure I 100% follow, but if you're doing it w/ PHP/WordPress, you can use `htmlentities` or `htmlspecialchars` (can't remember the difference) to do that encoding without an external framework (both are language-level functions). The code block needs to be encoded before it's spit out onto the page because that's how HTML works; it's not specific to Prism.

I don't think there's anything for us to do here, so I'm going to close, but feel free to follow-up w/ additional questions.
