### ISSUE TITLE
document highlight not working

### ISSUE THREAD

**Issue by troy351** [PrismJS/prism#2562]
**Information:**
- Prism version: 1.21.0
- Plugins: 'none'
- Environment: Chrome 85

**Description**
According to #1541 , `@param` in jsdoc should be highlighted, but it's not.

**Example**
![image](https://user-images.githubusercontent.com/8372385/93571873-a3cab380-f9c7-11ea-95cf-65cf344725dd.png)

https://codepen.io/troy351/pen/rNeZErz

**Comment by troy351** [comment]
fixed by adding two languages `<code class="language-js language-jsdoc">`, is this the right way to do it?

**Comment by RunDevelopment** [comment]
Since you're using Autoloader, you have to use [the `data-dependencies` attribute](https://prismjs.com/plugins/autoloader/#:~:text=Specifying%20additional%20dependencies): `<pre class="language-js" data-dependencies="jsdoc"><code>...</code></pre>`

Specifying multiple `language-xxxx` classes causes undefined behavior AFAIK. No idea why it worked in your example but it's not intentional.

**Comment by troy351** [comment]
Thanks for the explanation. Does this feature in the docs?
I have another question, if I use `prism.highlight`, how to add jsdoc support?

**Comment by RunDevelopment** [comment]
> if I use prism.highlight, how to add jsdoc support?

JSDoc will add itself to JavaScript as soon as it is loaded. This means you just have to ensure that both JS and JSDoc are loaded. (This is all `data-dependencies` does actually. It ensures that these languages are loaded before highlighting the code block.)

Please keep in mind that load order is important, so please don't load languages by their files directly. Always use either Autoloader, [`loadLanguages`](https://prismjs.com/#basic-usage-node), or our [babel plugin](https://prismjs.com/#basic-usage-bundlers).

> Does this feature in the docs?

I'm not sure what you mean by that.

**Comment by troy351** [comment]
Thanks again, I'll try that.
