### ISSUE TITLE
command-line plugin: how to use it in Markdown

### ISSUE THREAD

**Issue by hyperreal64** [PrismJS/prism#2573]
**Motivation**
I have a site that generates HTML web pages from Markdown. It's not obvious how to use the command line plugin with Markdown.

**Description**
I'd like to be able to use the command line plugin in Markdown code blocks. For example, something like:
```
```command-line, data-user=root,data-host=localhost,data-prompt=...
```
**Alternatives**
I haven't considered any feasible alternative solutions. I can just use plain HTML, but that defeats the efficiency of Markdown. :)

**Comment by RunDevelopment** [comment]
I don't think I follow. 

You write an application that converts some Markdown document into an HTML document (similar to [marked.js](https://marked.js.org/#usage) but as a website). You use Prism to highlight code blocks within the generated HTML document and now what to use Prism's [Command line plugin](https://prismjs.com/plugins/command-line/) for shell scripts.

Did I get this correctly? Because if I did, then I'm sorry but I don't understand the issue. 

Prism doesn't parse the Markdown (fenced) code blocks, so it's not responsible for converting the MD code blocks into HTML code blocks. From what I see, this is a pure configuration issue of your application or the library that you're using.

**Comment by hyperreal64** [comment]
No, the application I'm using that generates an HTML website from Markdown files uses PrismJS for code blocks' syntax highlighting in those Markdown files. I just want to be able to use the command line plugin without having to edit raw HTML. This may indeed be an issue with the way the site generator is configured. If so, then I apologize for opening an issue here.

**Comment by RunDevelopment** [comment]
If Prism is only used on code blocks on the generated HTML documents, then you'll have to open an issue in the repo of the site generator you're using.

However, adding support for Command line plugin to the site generator will most likely be non-trivial. Configuring the plugin isn't quite so simple and your proposed syntax for language specifier in fenced code blocks isn't compatible with [other commonly used formats](https://pandoc.org/MANUAL.html#pandocs-markdown#:~:text=A%20shortcut%20form%20can%20also%20be%20used%20for%20specifying%20the%20language%20of%20the%20code%20block).

Also, you might be interested in the `shell-session` language.

**Comment by hyperreal64** [comment]
`shell-session` should be good enough. It's not critically important to have the command-line plugin. The syntax for the language specifier I mentioned in the first comment was not proposed at all; it was meant to be a hypothetical example of how I'd like to use the plugin if there wasn't already a standard way to use it in Markdown.

Anyway, thanks, I guess.
