### ISSUE TITLE
[PHP] When code begins with class, class-name after it is not matched.

### ISSUE THREAD

**Issue by TomPavelec** [PrismJS/prism#2614]
**Information**
- Language: PHP
- Plugins: none

**Description**
When code begins with `class | interface | trait` the class-name after it is not matched.
When an whitespace is added before `class` the class-name is matched correctly.

I know that correct php code starts with `<?php` and then first class-name is matched correctly.
But opening tag is often dropped in code snippets fot better readability (blogs, docs, ..) and then this is an issue.

**Code snippet**

<details>
<summary>The code being highlighted incorrectly. Class name `First` is not matched.</summary>

```
class First {}
class Second {}
```

</details>

**Comment by RunDevelopment** [comment]
I'm late to reply, but here's an explanation of the bug:

The problem is that Prism lookbehinds don't actually look behind. Prism knows that greedy matches that start inside existing tokens will be discarded, so it skips over them (using `lastIndex`). This means that the class name pattern won't start matching at the start of the string but after the first `class` keyword. Since Prism lookbehinds can't look behind, they have no way of accessing the first `class` keyword and move on to find the second `class` keyword and `Second`.

The solution is to match all keyword-dependent class names before keywords are matched. That way you also don't need greedy matching.
(This is how we do it in most languages.)
