### ISSUE TITLE
Complex number in Scheme

### ISSUE THREAD

**Issue by jcubic** [PrismJS/prism#2641]
**Information:**
- Prism version: [e.g. 1.14, latest from the download page, etc.] Testing at website https://prismjs.com/test.html#language=scheme

**Description**
Complex number without imaginary number value is valid scheme complex number

**Example**
Example valid numbers that can be tested

```scheme
10+i
10+.1i
10+1.i
```

**Comment by jcubic** [comment]
I did few attempts to fix the number regex, but it was failing for other tests.

**Comment by RunDevelopment** [comment]
Seems like I used an old version of the spec when making the number pattern. I'll fix it soon.

Note to me: Page 62 of [this document](https://small.r7rs.org/attachment/r7rs.pdf) defines the grammar for a valid number.

**Comment by RunDevelopment** [comment]
@jcubic I have a question. I implemented it and now `10i`, `10.10i`, and `10e+10i` aren't tokenized as numbers anymore. This is because I implemented the BNF grammar on [page 62-63](https://small.r7rs.org/attachment/r7rs.pdf) literally (you only need to look at the `<complex R>` rule). They aren't valid numbers according to R7RS because they don't start with a sign (either `+` or `-`). Should I continue to follow the spec or should I relax it a little, so that the above numbers are tokenized again?

**Comment by jcubic** [comment]
All examples works in Kawa but not in Gauche, Guile and Racket those are my base implementations that I'm testing against (racket is not exactly Scheme but it's compatible). I've also found error in my implementation where `10e+10i` is parsed as `100.0`. The examples also work in my implementation (LIPS).

Maybe if Kawa support those, they can be marked as numbers, most of the time people will not use those type of values, because if they are not numbers they are treat as symbols so without quote '10 is marked as variable name, and they will use Kawa they would like to mark them as numbers.

**Comment by RunDevelopment** [comment]
If nobody is gonna these anyway, then I'll just keep the strict grammar.
