### ISSUE TITLE
Translations link dead

### ISSUE THREAD

**Issue by djdeo** [PrismJS/prism#2674]
**Information:**
- Prism version: [e.g. 1.14, latest from the download page, etc.]
- Plugins: [a list of plugins you are using or 'none']
- Environment: [e.g. Browser, Node, Webpack]

**Description**
`简体中文` link dead at root README.md file
`https://www.awesomes.cn/repo/PrismJS/prism` link won't open

**Comment by RunDevelopment** [comment]
Interesting. The whole site seems to be down. The link did work a few days ago, so let's wait a day or two for them to resolve any technical difficulties.

**Comment by edukisto** [comment]
The non-`https` [link](http://www.awesomes.cn/repo/PrismJS/prism) brings me to a page that shows an `iframe` with the following text:

> The website is currently inaccessible...
> 
> The website has not obtained an ICP filing according to the law of the Ministry of Industry and Information Technology of the People's Republic of China
> 
> Relevant law: Measures for the Archival Administration of Non-commercial Internet Information Services

**Comment by RunDevelopment** [comment]
Thank you for the info @edukisto!

So it's a bureaucracy issue. Just perfect... According to [this site](https://www.quantil.com/content-delivery-insights/icp-certification-china/#:~:text=It%20can%20take%204%2D8,the%20MIIT%20to%20receive%20one.), it takes about 4-8 weeks to get an [ICP filing](https://en.wikipedia.org/wiki/ICP_license). Seems like my "let's wait a day or two" turned into a month or two...

**Comment by edukisto** [comment]
@RunDevelopment, there is a [snapshot](https://web.archive.org/web/20200413183237/https://www.awesomes.cn/repo/PrismJS/prism) of the unavailable page. Unfortunately, [archive.org](https://web.archive.org) is [blocked in China](http://www.chinafirewalltest.com/?siteurl=https%3A%2F%2Fweb.archive.org%2F). The [snapshot of the snaphot](https://archive.today/2020.04.13-183237/https://www.awesomes.cn/repo/PrismJS/prism) is useless because of a broken slider. The [Google copy](https://webcache.googleusercontent.com/search?q=cache:https%3A%2F%2Fwww.awesomes.cn%2Frepo%2FPrismJS%2Fprism&strip=0&vwsrc=0) is broken, too.

There is also an older copy of the article on [DeepMind](https://deepmind.t-salon.cc/article/113).

Maybe, it would be nice to change or mark the broken link is some way?

* [简体中文](https://www.awesomes.cn/repo/PrismJS/prism) (temporarily unavailable; see copy [here](https://deepmind.t-salon.cc/article/113)).

**Comment by RunDevelopment** [comment]
@edukisto That seems like a good workaround. Thank you! I'll quickly change the readme.

**Comment by djdeo** [comment]
Thanks for the update,  I shall close the issue

**Comment by edukisto** [comment]
Looks like [awesomes.cn](https://www.awesomes.cn/repo/PrismJS/prism) is back.
