### ISSUE TITLE
Emoji issue with characters in Scheme

### ISSUE THREAD

**Issue by jcubic** [PrismJS/prism#2692]
**Information:**
- Prism version: Demo at https://prismjs.com/test.html#language=scheme

**Description**

Characters in Scheme are single character but it's problematic. I'm not sure if it's easy to solve by regex maybe it will require to update the core of the library.

The problem is character that is single emoji (or any Unicode character that have more then one code point):

**Example**
```scheme
#\💩
```
Copy this into editor and try to copy the result you will get #\� because even that emoji looks good in output it's splitted into two html element. It's not single span with the token.

The problem is probably only in Scheme or maybe other language that can have single character tokens that can be any Unicode characters.

Note: that copy/paste works fine on GitHub (try to paste into address bar).

I've found bug in my Scheme implementation and I've solved it by using [punycode](https://github.com/bestiejs/punycode.js) to test how many characters it have. Maybe you can use that as well since it will work with any versions. Just copy paste the function: `ucs2decode` from https://github.com/bestiejs/punycode.js/blob/master/punycode.js it probably don't change in the future or make punycode as dependency.

I'm not sure if there are any new Unicode regex features that can check for single character.

**Comment by RunDevelopment** [comment]
> I'm not sure if it's easy to solve by regex maybe it will require to update the core of the library.

It's easy. What you describe is what the [RegExp `unicode` (`u`) flags](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode) does. Unfortunately, we can't use that flag because of browser support (maybe in the future).

The reason why 💩 is problematic is that it takes 2 UTF16 characters to represent its Unicode code point. Our regex (`/#\\(?:[ux][a-fA-F\d]+\b|[-a-zA-Z]+\b|\S)/`) uses `\S` to handle single-character (UTF16) Scheme chars.

The fix is to replace `\S` without something that respects [surrogate pairs](https://en.wikipedia.org/wiki/UTF-16#Code_points_from_U+010000_to_U+10FFFF). We essentially have to emulate the behaviour of `/\S/u`. Fortunately, that's easy. While [the exact transpilation](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PQHQysCuQ&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015-loose&prettier=false&targets=&version=7.12.12&externalPlugins=) is quite complex, in our case, `/[\uD800-\uDBFF][\uDC00-\uDFFF]|\S/` will be sufficient.

I'll make a PR.
