### ISSUE TITLE
[BUG] clipboard js bundling - still uses cdn (privacy violation + prevents offline)

### ISSUE THREAD

**Issue by lmeyerov** [PrismJS/prism#2783]
**Information:**
- Prism version: download page
- Plugins: clipboard
- Environment: browser

Does the latest version of Prism from the [download page](https://prismjs.com/download.html) also have this issue? Yes

**Description**

When checking the clipboardjs plugin on the downloads page, the resulting bundle still attempts to contact a thirdparty website. This is unexpected, a problem for offline use, a privacy attack, and a security risk.

I recommend removing the plugin from the list to avoid misleading security-relevant behavior, or removing the surprise remote code execution.

Edit: See also https://github.com/PrismJS/prism/issues/2286 . I view this as a security bug , which was what caught our eye.

**Comment by joshgoebel** [comment]
> the resulting bundle still attempts to contact a thirdparty website

That's weird.  Which site/url?

**Comment by lmeyerov** [comment]
https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js

**Comment by lmeyerov** [comment]
I just bundled all the other plugins, and looks like 2 more potential ones:

-- https://webplatform.github.io/docs/ gets some funny string munging

-- http://www.w3.org/2000/svg some reason

clipboard definitely triggers on pageload

**Comment by joshgoebel** [comment]
Interesting.  The bundled code tries to require it `require("clipboard")` but if/when that fails it falls back to dynamically loading it via CDN. I'd say the bundler isn't sequencing things properly or else this expected behavior - though I would agree it seems quite unexpected to me.  If I chose to build with clipboard functionality "built-in" I would expect that to be part of the bundle, not fetched via CDN later.

**Comment by lmeyerov** [comment]
Ouch, so it's known, intentional, and hidden 😅

I recommend fixing the plugin download to be a plugin download, removing it from the download list, or keeping it in the download list and notifying the downloader that it isn't actually being downloaded etc

**Comment by joshgoebel** [comment]
I can't speak for the core team, but I see both sides here.  Prism.js is only bundling ITSELF (and it's plugins).  It's not promising to bundle the world or EVERY necessary dependency.  If a plugin depended on jQuery or React I wouldn't expect those to magically come bundled... _but I do think that just loading it randomly is potentially surprising behavior._    Perhaps an error should be raised instead. 

Curious to see where this issue goes. :)

**Comment by RunDevelopment** [comment]
We use Clipboard.js because there is no easy cross-browser way to copy text into the user's clipboard.

I think the easiest solution here is to eliminate the dependency. Implementing our own copy to clipboard functionality will be __a lot__ easier than making our download page a general bundler. (Our download page isn't a bundler like Rollup. It can only resolve dependencies between languages using Prism's own dependency system.)

Thoughts?

/cc @mAAdhaTTah 

---

> I just bundled all the other plugins, and looks like 2 more potential ones:
> 
> -- https://webplatform.github.io/docs/ gets some funny string munging
> 
> -- http://www.w3.org/2000/svg some reason

The [WPD plugin](https://prismjs.com/plugins/wpd/) only creates links to those sites, it doesn't directly connect to them.
