### ISSUE TITLE
How to maked sql language？

### ISSUE THREAD

**Issue by superhuai** [PrismJS/prism#2828]
**Information**
- Language: [e.g.JavaScript, YAML, etc.]
- Plugins: [a list of plugins you are using or 'none']

**Description**
when i set `language-sql` ，it‘s not work! 
env : React

**Code snippet**

[Test page](https://codesandbox.io/s/optimistic-montalcini-lsirr?file=/src/App.js)

<details>
<summary>The code being highlighted incorrectly.</summary>

```
Your code goes here
```

</details>

**Comment by RunDevelopment** [comment]
[Here](https://codesandbox.io/s/beautiful-platform-k1gor?file=/src/App.js) is a "fixed" version of your project. 

Prism is modular by design and the default export only includes very few languages, SQL is not one of them. So we have to load SQL ourselves. In the "fixed" version, I did this via directly importing the file but this **not** a good idea because it completely ignores Prism's dependency system. I recommend using [our babel plugin](https://github.com/mAAdhaTTah/babel-plugin-prismjs) instead. Our babel plugin will automatically generate imports for all the languages you specified without having to worry about Prism's dependency system.
