### ISSUE TITLE
Created new Language / How to push it?

### ISSUE THREAD

**Issue by gianluca1606** [PrismJS/prism#2877]
Hello guys, i have created a new language definition for RPG. Or to be more precise fully free rpg.

I also have written the tests and everything seems to work fine, at least better then without any syntax highlighting 👯 

Since i am not a git expert i would like to push the new language into the repository but i do not know how to do it correctly.
Furthermore while building prism it looks like a lot of other files have been changed ( the min files that are auto generated)... Should i commit them also or it is not necessary to commit them again ?

Can someone help me how to proceed ?

Thanks in advance

**Comment by RunDevelopment** [comment]
Hello @gianluca1606! Thank you for wanting to contribute! 

Here are 2 guides on how to get started: [1](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/), [2](https://github.com/firstcontributions/first-contributions). The second one even includes instructions on how to do it in your IDE of choice. I hope this helps.

> Furthermore while building prism it looks like a lot of other files have been changed ( the min files that are auto generated)...

That means that you installed a different version of uglify (the code minifier we use). This happened because `npm install` is __not__ determinist (the install result depends on various factors...). We added a `package-lock.json` to get around this. Instead of using `npm install` to install our dependencies, use `npm ci`. `npm ci` guarantees to install exactly the packages we want, 100% of the time.

(Make sure to revert any changes to `package-lock.json` before running `npm ci`.)

---

If you have any further questions or get stuck, feel free to comment.

**Comment by gianluca1606** [comment]
> Hello @gianluca1606! Thank you for wanting to contribute!
> 
> Here are 2 guides on how to get started: [1](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/), [2](https://github.com/firstcontributions/first-contributions). The second one even includes instructions on how to do it in your IDE of choice. I hope this helps.
> 
> > Furthermore while building prism it looks like a lot of other files have been changed ( the min files that are auto generated)...
> 
> That means that you installed a different version of uglify (the code minifier we use). This happened because `npm install` is **not** determinist (the install result depends on various factors...). We added a `package-lock.json` to get around this. Instead of using `npm install` to install our dependencies, use `npm ci`. `npm ci` guarantees to install exactly the packages we want, 100% of the time.
> 
> (Make sure to revert any changes to `package-lock.json` before running `npm ci`.)
> 
> If you have any further questions or get stuck, feel free to comment.

Okay, so now i cloned the repository again and made my changes. With npm ci and npm build i only have 16 changed files. 

I already commited my new files, the tests for RPG and the language definition..

Now there are only 6 files missing a commit:

![image](https://user-images.githubusercontent.com/61363342/116387904-9312d380-a81b-11eb-91cb-73d8cb6e3f7f.png)

What message should i add to them, since some of them are auto generated I do not really know what i should write there?

**Comment by RunDevelopment** [comment]
Yes, those 6 files also have to be committed. As for the commit message... idk. Maybe "Updated components.json"? All these files changed because of `components.json` after all.

**Comment by gianluca1606** [comment]
> Yes, those 6 files also have to be committed. As for the commit message... idk. Maybe "Updated components.json"? All these files changed because of `components.json` after all.

Okay i tried to push now with:
Git push origin master
I keep receiving this error message: prism git:(master) git push origin master
remote: Permission to PrismJS/prism.git denied to gianluca1606.
fatal: unable to access 'https://github.com/PrismJS/prism.git/': The requested URL returned error: 403

What I am doing wrong ? 👯 
Sorry i know it is probably a stupid question but i am a git newbie.

**Comment by RunDevelopment** [comment]
There are no stupid questions. We all had our troubles learning git at some point.

>  I keep receiving this error message: prism git:(master) git push origin master
> remote: Permission to PrismJS/prism.git denied to gianluca1606.
> fatal: unable to access 'https://github.com/PrismJS/prism.git/': The requested URL returned error: 403

That is because tried to push to the wrong repository. You tried to push to the master branch of this repository. This failed (as it should) because you don't have write access to the PrismJS/prism repo (= the repo the PrismJS team owns). You only have write access to your fork, your gianluca1606/prism repo.

I guess you cloned the wrong repo. You always want to clone your fork.

The easiest solution for this to set up the project again but this time you clone your fork. This means that you have to apply and commit your changes again. But on the upside, you will learn the correct workflow. 

Also, I noticed that you committed directly to master instead of a new branch. This can work but is not recommended. I highly recommend that you make a new branch for your changes.

**Comment by RunDevelopment** [comment]
Oops, I didn't see your PR. Glad you figured it out!

**Comment by gianluca1606** [comment]
> Oops, I didn't see your PR. Glad you figured it out!

Yes but i had not created the new branch and i kind of mixed some of the steps so now i repeated everything again. 

I saw there is some error with the aliases and I think i fixed it now. I missed the [] at the language definition file.

Now that i have everything correct in a specific branch "RPG-Support" [Github-Repo](https://github.com/gianluca1606/prism) should i close the one pull request and create a new one ? 

Sorry for taking your time :) and thanks a lot for your help i learned a lot of new things today.

**Comment by RunDevelopment** [comment]
> should i close the one pull request and create a new one ?

Yes, please.
