### ISSUE TITLE
`sql` language syntax highlighting table names as keyword

### ISSUE THREAD

**Issue by dyapasrikanth** [PrismJS/prism#2895]
``` html
<pre><code class="language-sql">
SELECT USER.name
        FROM USER where something='nothing'
</code></pre>
```

`USER` is a table name but its highlighting that as keyword just like `SELECT` & `FROM`.

PrismJS version: 1.23.0

**Comment by RunDevelopment** [comment]
That's because [`USER`](https://docs.microsoft.com/en-us/sql/t-sql/functions/user-transact-sql?view=sql-server-ver15) is a [reserved keyword](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15). As stated in [the documentation](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers?view=sql-server-ver15#rules-for-regular-identifiers):

> [...] The identifier must not be a Transact-SQL reserved [key]word. SQL Server reserves both the uppercase and lowercase versions of reserved [key]words. When identifiers are used in Transact-SQL statements, the identifiers that do not comply with these rules must be delimited by double quotation marks or brackets. [...]

Therefore, Prism highlighting `USER` as a keyword is correct.

That being said, Prism doesn't currently support bracket identifiers, so I'll quickly add that.

**Comment by RunDevelopment** [comment]
> That being said, Prism doesn't currently support bracket identifiers, so I'll quickly add that.

Upon closer inspection, no. I won't add them. Bracket identifiers are non-standard SQL [specific to Microsoft SQL](https://stackoverflow.com/a/52910/7595472). They are also directly incompatible with other SQL dialects.

I will now close this issue because the highlighting is correct.

**Comment by joshgoebel** [comment]
> Upon closer inspection, no. I won't add them. Bracket identifiers are non-standard SQL 

Good call I think.  We recently redid our SQL grammar to be just "standard SQL" (largely)... if someone wants to support a more specific dialect that can always be done with a specific grammar for that dialect, not the primary SQL grammar.

Often SQL dialects have 100s of their own keywords also, etc...
