### ISSUE TITLE
Coy theme is broken with line highlight plugin

### ISSUE THREAD

**Issue by philippklodt** [PrismJS/prism#2989]
This can be verified on the official web site of the line-highlight plugin and selecting the "Coy theme":
https://prismjs.com/plugins/line-highlight/
The bottom most examples (starting at "Compatible with Line numbers") are not working: When scrolling, the line highlighting does not move with the line.
The problem is not present with the other themes (haven't checked all though)

prismJs version: 1.24.1

**Comment by cyfung1031** [comment]
![qscsdaa](https://user-images.githubusercontent.com/44498510/127366645-49681b1b-fafa-4b1a-a556-60d4e9d4fc02.PNG)

It seems to be intentional to break the plugin ??

**Comment by RunDevelopment** [comment]
@cyfung1031 This bug has nothing to do with those lines of CSS.

Coy is kinda the black sheep of our themes. The problem is that Coy uses the `code` element to scroll the text while all other themes use the `pre` element. This small difference causes a lot of problems.

We will likely replace Coy with the [Coy without Shadows](https://github.com/PrismJS/prism-themes/blob/master/themes/prism-coy-without-shadows.css) theme in v2. It looks almost the same but doesn't have these problems.

**Comment by RunDevelopment** [comment]
I just went through old issues and noticed that this is a duplicate of #1666. I'll close this now.
