### ISSUE TITLE
Autoloader doesn't load javascript when loading markup?

### ISSUE THREAD

**Issue by marcelklehr** [PrismJS/prism#2996]
**Information:**
- Prism version: latest v1.x rom cdn
- Plugins: autoloader
- Environment: browser

**Description**
When using the autoloader plugin, and highlighting html with script tags with javascript in them, the javascript is not highlighted. Likely because the javascript langauge is not loaded by the autoloader plugin.

I'm loading the following files from cdn:

   - https://cdn.jsdelivr.net/npm/prismjs@v1.x/components/prism-core.min.js
   - https://cdn.jsdelivr.net/npm/prismjs@v1.x/plugins/autoloader/prism-autoloader.min.js

I've even tried loading the javascript component file (and some others) myself from the cdn but it doesn't work either:

   - https://cdn.jsdelivr.net/npm/prismjs@v1.x/components/prism-core.min.js
   - https://cdn.jsdelivr.net/npm/prismjs@v1.x/components/prism-clike.min.js
   - https://cdn.jsdelivr.net/npm/prismjs@v1.x/components/prism-javascript.min.js
   - https://cdn.jsdelivr.net/npm/prismjs@v1.x/components/prism-css.min.js
   - https://cdn.jsdelivr.net/npm/prismjs@v1.x/components/prism-markup.min.js
   - https://cdn.jsdelivr.net/npm/prismjs@v1.x/plugins/autoloader/prism-autoloader.min.js

**Example**
#### My site

https://magpie-manual.netlify.app/00_getting_started/03_vue_js.html

#### Your site

https://prismjs.com/test.html#language=markup

I'm not sure if you are using the autoloader here, but try entering `<script>console.log('fooo')</script>`. It will not get highlighted until you select Javascript once and go back to markup in the language settings.

**Comment by RunDevelopment** [comment]
JS and CSS both modify Markup in order to add highlighting to `<script>` and `<style>` tags. This means that Markup has to be loaded before JS and CSS. However, since highlighting for `<script>` and `<style>` tags is optional, Autoloader won't load JS and CSS if you only request Markup. 

There are two ways to solve your issue:

1. [`data-dependencies`](https://prismjs.com/plugins/autoloader/): This is the intended way to use Autoloader.
2. Instead of loading `prismjs@v1.x/components/prism-core.min.js`, use `prismjs@v1.x/prismjs.js`. This build of Prism includes Markup, JS, and CSS from the start, so Autoloader only has to load languages besides those three.

**Comment by marcelklehr** [comment]
@RunDevelopment Thanks Michael! Works as intended now :)
