### ISSUE TITLE
Firefox padding right

### ISSUE THREAD

**Issue by worldsdream** [PrismJS/prism#2999]
In the browsers Microsoft Edge, Chrome, it works great. In Firefox, the code does not have spacing in the right padding. Please see screenshots. Screenshots are taken from https://prismjs.com/.

![Edge](https://user-images.githubusercontent.com/12443285/126043884-21302b12-bdf0-4237-afb8-92d25dac7a9b.png)

![Firefox](https://user-images.githubusercontent.com/12443285/126043887-7affd97b-6a96-45a8-9c57-96d780ba6b53.png)

Can this be fixed for Firefox users in a next build please?

**Comment by RunDevelopment** [comment]
This seems to be [a bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=748518). It seems like Firefox ignores the `padding-right` and `padding-bottom` properties if scrollbars are present for those directions. [It's not just us](https://stackoverflow.com/questions/29986977/firefox-ignores-padding-when-using-overflowscroll).

The FF bug seems to have had some attention recently, so hopefully it will be fixed within a year or so.

I don't think it's something that we should/have to fix. The bug is well-documented and the recent attention in this and related issues suggest that the bug will be fixed soon-ish (~ 1 year). The bug also doesn't affect our users too badly. I doubt many users will even notice it.
