### ISSUE TITLE
Dark block on code

### ISSUE THREAD

**Issue by nerdthatnoonelikes** [PrismJS/prism#3024]
**Information:**
- Prism version:  latest from the download page
- Plugins: line numbers, show language, copy to clipboard button, and toolbar

**Description**
Code examples are highlighted with a dark color. I'm not sure if this is because of a plugin I am using or if its just an issue for me.

**Example**
![image](https://user-images.githubusercontent.com/33642056/127783662-a4d3afd7-922f-4a73-9454-d89bffe05f5a.png)

**Comment by RunDevelopment** [comment]
> or if its just an issue for me.

That's most likely the case here. Issues that cannot be reproduced on [prismjs.com](https://prismjs.com/#plugins) are typically due to styles from other CSS files being applied to the `pre` or `code` elements. In this case, it seems like some other CSS file is setting the background of the `code` element. 

Could you please check which file (or rule) is setting the background of the `code` element?

**Comment by nerdthatnoonelikes** [comment]
Fixed! I had CSS that was being applied to another `code` element. Thanks for the help. 😄
