### ISSUE TITLE
Next.js - Line numbers are out of sync with the lines

### ISSUE THREAD

**Issue by AlexTechNoir** [PrismJS/prism#3045]
**Information:**
- Prism version: ^1.24.1
- Plugins: line-numbers, line-highlight, autolinker, highlight-keywords, inline-color, previewers, data-uri-highlight, copy-to-clipboard
- Environment: Chrome, Next.js, Webpack

**Description**

In addition to my previous issue, I just noticed that Line Number plugin renders numbers out of sync with lines.

**.babelrc:**

```
...
    ["prismjs", {
      "languages": ["javascript", "css", "markup", "bash", "git", "graphql", "gitignore", "json", "jsx", "regex" ],
      "plugins": [
        "line-numbers", 
        "line-highlight", 
        "autolinker", 
        "highlight-keywords", 
        "inline-color", 
        "previewers", 
        "data-uri-highlight",
        "copy-to-clipboard"
      ],
      "theme": "okaidia",
      "css": true
    }]
...
```

![1](https://user-images.githubusercontent.com/43852391/130675135-1f2a2444-3a0a-4a10-a38e-6dc24d0a8aa3.jpg)

**Example**
Apologies, I can't give an example, because I haven't deployed HCMS yet (data comes from there).

**Comment by RunDevelopment** [comment]
From the font family, I can see that styles from your website are overriding the styles of Okaidia. [This plugin page](https://prismjs.com/plugins/line-numbers/) is a working example.

This might be because you used one `!important` too many or because Prism's CSS style sheet is imported before the styles for the rest of your site.

Either way, it's not Prism's fault.
