### ISSUE TITLE
Markdown front matter highlighting not the same as YAML?

### ISSUE THREAD

**Issue by Josh-Cena** [PrismJS/prism#3283]
**Information**
- Language: Markdown
- Plugins: none

**Description**

YAML keys and values have different highlighting; however, all Markdown front matter is treated as plain string.

I'm aware that #2634 adds support for front matter, but that still doesn't make front matter displayed the same as YAML.

| Highlight as MD | Highlight as YAML |
|---|---|
| ![image](https://user-images.githubusercontent.com/55398995/147434502-9eb1b598-7010-49fe-abde-2c5b28946132.png) | ![image](https://user-images.githubusercontent.com/55398995/147434553-ede52126-9d5e-4091-8789-7fdde1170bb4.png) |

**Code snippet**

[Test page](https://prismjs.com/test.html#language=markdown&text=%2F%2F%20Good%20comment%0A%2F%2F%20Good%20comment%0Aconst%20a%20%3D%20'%2F*'%3B%0A%2F%2F%20Still%20good%0A%2F%2F%20Not%20correctly%20parsed!%20(keyword%20like%20return)%0Aconst%20b%20%3D%20true%3B%0A%2F%2F%20Still%20bad%20comment%0A%2F*%20Some%20block%20comment%20*%2F%0Aconst%20c%20%3D%201%3A%0A%2F%2F%20I%20am%20good%20again%0A)

<details>
<summary>The code being highlighted incorrectly.</summary>

```md
---
id: 1
title: Hello
---

## Hello 

aaa
```

</details>

**Comment by RunDevelopment** [comment]
It does work, it's just a little difficult to do on the test page.

![image](https://user-images.githubusercontent.com/20878432/147469522-3e2ada70-6a85-4a6a-b7bc-f1e2c9561020.png)


Prism's languages have dependencies. I.e. Markdown (optionally) depends on YAML to highlight front matter. Prism does not resolve dependencies itself and assumes that languages are loaded in the correct order to satisfy all their dependencies. I.e. YAML has to be loaded *before* Markdown; Markdown won't be able to see YAML otherwise.

So to see front matter being highlighted on the test page, you have to do the following:

1. Enter your MD code on the test page.
2. Select the YAML language.
3. Reload the page. (This will cause the test page to unload all languages and then load only YAML.)
4. Select the Markdown language. (Markdown will now be loaded. Since YAML has been loaded before Markdown, Markdown will be able to see YAML and use it for front matter.)

 I know that this is quite cumbersome, but this very manual approach to language loading on the test page is great for testing.

**Comment by Josh-Cena** [comment]
Thanks for your explanation! I've managed to fix it on our side.
