### ISSUE TITLE
JavaScript Misclassification Before Method Named Bind

### ISSUE THREAD

**Issue by twodee** [PrismJS/prism#3298]
**Information**
- Language: JavaScript
- Plugins: none

**Description**
I'm trying to highlight some JavaScript that has a call to a method named `bind`. The particular name `bind` causes the token of the invoking object to be classified as a function and is therefore highlighted differently than other invoking objects. For example, in `foo.bind()`, the token `foo` is treated as a function.

**Code snippet**

[Test page](https://prismjs.com/test.html#language=javascript&text=function%20setColor(r%2C%20g%2C%20b)%20%7B%0A%20%20shaderProgram.bind()%3B%0A%20%20shaderProgram.setUniform3f(%22color%22%2C%20r%2C%20g%2C%20b)%3B%0A%20%20shaderProgram.unbind()%3B%0A%20%20render()%3B%0A%7D)

<details>
<summary>The code being highlighted incorrectly.</summary>

```
function setColor(r, g, b) {
  shaderProgram.bind();
  shaderProgram.setUniform3f("color", r, g, b);
  shaderProgram.unbind();
  render();
}
```

</details>

**Comment by RunDevelopment** [comment]
Thank you for the report!

[`someFunction.bind(thisArg, arg1)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind) is a relatively common pattern, so Prism detects all `.bind` function calls and highlights the caller as a function. Your bug is a false positive of this heuristic.

Since we don't (and will never) have access to type information, we can't fix this false positive, unfortunately.

**Comment by twodee** [comment]
Thanks for the response. I see what you mean.

Wouldn't it be more consistent to treat the token for the invoking object according to its syntactic context? Why not treat the predecessor to `bind`, `apply`, and `call` as an object? Isn't that how the grammar would classify it?

The decision about what is or is not a function seems fuzzy. Why not classify `foo` in `foo.prototype` as a function?

**Comment by twodee** [comment]
I see #1471 now. Looks like I hit one of those very few occasions. If there's no chance to configure when these assumptions are made, I'll just make a fork.

**Comment by RunDevelopment** [comment]
> Wouldn't it be more consistent to treat the token for the invoking object according to its syntactic context? Why not treat the predecessor to `bind`, `apply`, and `call` as an object? Isn't that how the grammar would classify it?

I'm sorry, but I don't understand what you mean. Could you describe this in a bit more detail.

> The decision about what is or is not a function seems fuzzy.

That's because it is impossible to guess what variable is a function from syntax alone. We would need full TypeScript type information (or similar) to do that. We have no choice but to make guesses and assumptions to deliver good highlighting.

> Why not classify `foo` in `foo.prototype` as a function?

We already do this for classes. However, we do require the class name to start with an upper-case letter to prevent some false positives.

![image](https://user-images.githubusercontent.com/20878432/149324652-d5bad210-69b2-4415-aee6-62dfe08b7ef7.png)

> If there's no chance to configure when these assumptions are made, I'll just make a fork.

You don't need a whole fork to change a single token. Prism grammars are mutable, so you can just change [this token](https://github.com/PrismJS/prism/blob/8458c41fab59d84bcb936f0d72a14dd91503460c/components/prism-javascript.js#L20) to remove the `bind`.

However, I can think of one possible fix. `bind` require at least one argument, and we could check that. This would solve your false positive. It's not a perfect fix, but maybe it's enough.

**Comment by twodee** [comment]
Changing a single token is a great idea. Thanks for the suggestion!

I'm not going to try develop my other earlier suggestion more. Classifying an identifier in Javascript is an impossible task. The most I can ask for is the flexibility to modify the behavior to suit my situation, and you've pointed out that I have that.
