### ISSUE TITLE
Line Highlight background does not strech full width

### ISSUE THREAD

**Issue by Aberdeener** [PrismJS/prism#3426]
**Information:**
- Prism version: 1.27
- Plugins: line-highlight, line-numbers
- Environment: browser

**Description**
I use Prism to display errors during a web app runtime, and highlight the specific line that threw the error.
Usually these files that I display in prism have long lines, which make the prism container have a horizontal scroll bar.

However, the line highlight background fades out at the end of the original size of the container, so when I scroll on the horizontal bar, the line is not highlighted after a certain point.

**Example**
Video:
https://user-images.githubusercontent.com/26070412/161865358-9735db31-2509-46ad-9f82-9578d64b4483.mov

Code:
https://raw.githubusercontent.com/NamelessMC/Nameless/bugfix/prism/error.tpl

Thank you

**Comment by Aberdeener** [comment]
I fixed this by changing
https://github.com/PrismJS/prism/blob/8a3fef6dcc4ed92f0ff0be5765c6d59bde87d493/plugins/line-highlight/prism-line-highlight.js#L200

to

```js
line.style.width = pre.parentNode.offsetWidth + ((pre.parentNode.offsetWidth - pre.scrollWidth) * 2);
```

I don't know if this is a bug or an intended feature?
Please advise before I PR

**Comment by RunDevelopment** [comment]
> a bug or an intended feature?

A bug and one on your end. It does work on [our plugin page](https://prismjs.com/plugins/line-highlight/#linkable.50), so I don't know why it doesn't work on your website.

Your template looks fine:
```tpl
<pre data-line="{$frame['highlight_line']}" data-start="{$frame['start_line']}"><code class="language-php line-numbers">{$frame['code']}</code></pre>
```

So the problem is most likely with some style. Are you using the Coy theme (or a variation based on it)? I'm asking because Coy has compatibility problems with many plugins. If you are, using [Coy with shadows](https://github.com/PrismJS/prism-themes/blob/master/themes/prism-coy-without-shadows.css) will most likely fix the issue.

Also, I don't understand why looking at the [`offsetWidth`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetWidth) of the parent element would help us solve this issue.

**Comment by Aberdeener** [comment]
Sorry, I should have mentioned that - I am using the Coy theme yeah.
Only minor style changes to it (in the same file I linked originally), but this issue occurs even without those customizations.

Thank you

**Comment by RunDevelopment** [comment]
> but this issue occurs even without those customizations.

Yes, Coy is fundamentally incompatible with a few plugins because of the way it is implemented. This is why I suggested Coy with shadows. It's a theme that looks like Coy but without the compatibility issues.

> Thank you

You're welcome. I take the issue is solved then?

**Comment by Aberdeener** [comment]
Yep, closed!
Have a nice day, and thanks for your work on Prism.

**Comment by webzille** [comment]
This isn't a bug. It's part of CSS.

```css
.line-highlight {
	position: absolute;
	left: 0;
	right: 0;
	padding: inherit 0;
	margin-top: 1em; /* Same as .prism’s padding-top */

	background-color: hsla(24, 20%, 50%,.08);
	/*background: linear-gradient(to right, hsla(24, 20%, 50%,.1) 70%, hsla(24, 20%, 50%,0));*/

	pointer-events: none;

	line-height: inherit;
	white-space: pre;
}
```
I did changed `background: hsla(24, 20%, 50%,.08);` to `background-color: hsla(24, 20%, 50%,.08);` and commented out the linear-gradient and now the line takes the full width of the code/pre container
