### ISSUE TITLE
No highlighting option?

### ISSUE THREAD

**Issue by GuiTeK** [PrismJS/prism#344]
I'd like to create a code block with some Apache configuration, however, there is no such language definition for Prism at the moment.

I'd be happy with just a code block with plain black text and no syntax highlighting but I couldn't find a way to do that.
* Does such a feature exist?
* If not, should it be added?
* Or would it be preferred to write the definition for the Apache conf syntax?

**Comment by brandones** [comment]
`language-none` is a great idea. I'd call it `language-plaintext`. Not having coverage for every format in existence is not a bug.

**Comment by brandones** [comment]
For those finding this later -- Prism now formats `<pre>` tags even if no valid language is specified!

**Comment by jfcere** [comment]
@brandones has per v1.16 having a `<pre><code>I am only text</code></pre>` does not seems to be displayed as a code block.

![image](https://user-images.githubusercontent.com/6987084/55598575-64e86580-5721-11e9-8a96-6ef387a4b3bd.png)

Am I missing something?

**Comment by RunDevelopment** [comment]
> [...] even if no __valid__ language is specified!

@jfcere I think Prism used to not work when the specified language was unknown to Prism. 
So, no. We don't support `<pre><code>` without a `language-xxxx` class for at least one of the elements.

**Comment by jfcere** [comment]
@RunDevelopment thanks for your follow up.

Is this something you guys would be willing to do? I could do the PR if you guys agree.

Although I could be wrong, I think it is pretty much expected that `<pre><code>` are displayed as code block even if there is no `language-xxxx`. The only reason I could think for not doing it is that it could be interpreted as too intrusive.

Anyhow, I'll respect your decision and will find my way around this if the proposition is rejected.

**Comment by mAAdhaTTah** [comment]
The underlying issue is most themes do [something like this](https://github.com/PrismJS/prism/blob/master/themes/prism-coy.css#L7-L8) to style `pre` & `code` elements. I do think it would be too intrusive to apply styles to _every_ `pre` & `code` because we can't assume all of them will be touched by Prism (in fact, if it doesn't have a language Prism core will ignore them). Seems like the themes should follow suit, so I'm inclined to reject that suggestion.

This also would technically be a breaking change, as we're now styling things we weren't before, and would require consumers to overwrite our styles if they didn't want them.

**Comment by RunDevelopment** [comment]
@jfcere I think that this would create the problem that you can't opt out anymore.

Right now, Prism is strictly opt-in meaning that only the code blocks you give a special `language-xxxx` class are affected by Prism.
So if we change this, we should also include an opt-out option.

I don't know if this is worth the hassle, plus it would be a breaking change as @mAAdhaTTah pointed out while I wrote this.

Also, Prism supports the inheritance of `language-xxxx` classes. So you could just give your `<body>` the class `language-none` and every block will be highlighted which means that plugins like e.g. line number and CSS styles will also be applied.
So, do we even need to change anything?

**Comment by jfcere** [comment]
Alright, I understand and it makes a lot of sense.

My situation is different because I am using Prism inside Angular framework which only applies Prism on specified elements instead of the whole page making the concern of not wanting the code to be highlighted for a certain element irrelevant in that context (see [ngx-markdown](https://github.com/jfcere/ngx-markdown)).

Thanks again for your follow up and this awesome library!

**Comment by RunDevelopment** [comment]
In that case, I assume that it is not possible to call the `Prism.highlightElement` function yourself?

It will behave a little strangely, but it should work. (If I read the code correctly, you'll get nice little `language-undefined` class.)

On that note: Maybe we should make it so that `language-none` is the default in the case that `highlightElement` can't detect a `language-xxxx` class instead of `language-` or `language-undefined` @mAAdhaTTah ?

**Comment by mAAdhaTTah** [comment]
You could [wire a customer renderer](https://github.com/jfcere/ngx-markdown#markedoptionsrenderer) to change inline code blocks to have the expected class.

**Comment by LeaVerou** [comment]
FWIW, I agree with the others about not targeting class-less `<pre>`s and `<code>`s. Do note that since language classes inherit, targeting all of them can be as simple as applying `language-none` to your `<html>`, `<body>` or any other shared ancestor.

> On that note: Maybe we should make it so that `language-none` is the default in the case that `highlightElement` can't detect a `language-xxxx` class instead of `language-` or `language-undefined`

Yeah, that sounds like a nice little fix, so that code listings with no language can be styled with one class. I wonder if there's any value in distinguishing the two cases though.

**Comment by RunDevelopment** [comment]
> I wonder if there's any value in distinguishing the two cases though.

I don't think there is.
TBH I don't even think that the `language-` case is possible when [looking at the code](https://github.com/PrismJS/prism/blob/e268395920bdda1d07dc73e3b2268eeace6ac81f/components/prism-core.js#L199). I can't imagine a case where `parent.className.match(lang)` returns `null`.

**Comment by conventions-postwar630** [comment]
Tune into this https://angulars.space/questions/illuminating-javascript-code-with-the-help-of-ngx-prism answer
