### ISSUE TITLE
Safari Reader hides comments

### ISSUE THREAD

**Issue by apparebit** [PrismJS/prism#3466]
**Information:**
- Prism version: latest from the download page
- Plugins: none
- Environment: Safari on macOS and iOS

**Description**

Safari Reader hides spans for comments, most likely because they are annotated with the "comment" class. A different class name might be called for, though I did not test whether a prefix such as "source-" would suffice.

**Example**

Visit https://apparebit.com/blog/2021/lets-try-again and look at the code example towards the end of the post in version 15.5 of the Safari browser (either macOS or iOS). 

The regular appearance is just as expected:
![image](https://user-images.githubusercontent.com/3990077/172490978-65f07dc7-8aed-409b-b65e-4d061b5020b5.png)

But when looking at the same code block with Safari Reader, all Python comments are MIA:
![image](https://user-images.githubusercontent.com/3990077/172491147-31f9e7c5-2a93-4cc6-a645-e935d0e3bfd4.png)

I understand if you consider this a Safari bug and won't fix. I have also [tweeted about the bug](https://twitter.com/apparebit/status/1534209752036696064) at WebKit. But this is a good example of Prism's generic class names having unexpected side effects.

**Comment by RunDevelopment** [comment]
> But this is a good example of Prism's generic class names having unexpected side effects.

This isn't a side effect of Prism's class names so much as it is other software making assumptions on how class names are used.

Also, this effect can be intentional in some cases for whatever reason. We had this before in #2314.

> I understand if you consider this a Safari bug and won't fix.

Yes, we don't consider this to be a bug with Prism.

---

Anyway, as you suggested, using a prefix will fix this. You can use our [Custom Class plugin](https://prismjs.com/plugins/custom-class/) to replace all `comment` classes with something else (e.g. `prism-comment`) like this:

```js
Prism.plugins.customClass.map({
	comment: 'prism-comment',
});
```

Don't forget to change the CSS of your theme as well, or else comments won't get any color.

**Comment by apparebit** [comment]
Thank you for the pointer to the custom class plugin; that nicely solves the problem. And sorry for missing #2314. I did search for "Safari Reader" before opening the issue.
