### ISSUE TITLE
Replace JSDoc as it is not maintained and is legacy software

### ISSUE THREAD

**Issue by ShukantPal** [PrismJS/prism#3485]
Hi folks, JSDoc is [no longer being actively maintained](https://github.com/jsdoc/jsdoc/commits/main) and that's why I built a better, maintainable toolset called [webdoc](https://www.webdoclabs.com?utm_campaign=melonjs&utm_source=ni&utm_medium=GitHub). webdoc has a more [modern theme](https://webdoc-labs.github.io/example-documentation/index.html) that's fully customizable! I would be down to helping you move your documentation to webdoc, the choice is up to you.

I think webdoc will bring a lot of clarity to your existing documentation, and it is pretty good for this use case. See melonJS [docs](http://melonjs.github.io/melonJS/docs/), which are built with webdoc now; webdoc will remain free for open source projects like PrismJS!

**Comment by RunDevelopment** [comment]
@ShukantPal We use JSDoc because it is a tool that fits our needs. So I am sorry to say that we will not be switching to your documentation generator anytime soon. I have also previously used and contributed to TSDoc, so the choice after JSDoc is clear. That being said, I do appreciate the offer to improve Prism's docs. Thank you.

I also want to point out that while it is great that webdoc will be free for OSS, open source projects typically prefer (or even require) their dependencies to be open source with well-known (preferably permissive) licenses. We are not lawyers and as such it is hard to judge how permissive or restrictive webdoc's non-commercial license is. The other open source projects you contacted (https://github.com/sql-js/sql.js/issues/520, https://github.com/beefproject/beef/issues/2458) might have similar concerns.

So while I do appreciate the offer, Prism currently has no need for a different documentation generator, and webdoc's license makes it harder to adopt.

**Comment by ShukantPal** [comment]
Thanks @RunDevelopment for replying. If I may, am curious about a few questions :)

Is the concern that webdoc's license would pollute Prisms license because it's marked as a dependency?

If webdoc ran in the cloud / CI so you don't download closed source code at all, would it still be a concern?
