### ISSUE TITLE
highliting missing after re-refresh

### ISSUE THREAD

**Issue by sytpb** [PrismJS/prism#3530]
react 18 

![60e84984b758ecddf72fb0f1df95a73](https://user-images.githubusercontent.com/12178686/185863542-a8077db7-5925-40c9-9c1e-25d459691d90.png)

![image](https://user-images.githubusercontent.com/12178686/185863662-1ffd3066-d34e-49fe-9c37-d41ca529e8b8.png)

![606671233f658b875df548805234618](https://user-images.githubusercontent.com/12178686/185863577-4e315d2b-a1d4-41fd-bb0e-d9a60abb097e.png)

```
import React, { useEffect } from "react";
import Prism from "prismjs";
import styles from './code.module.css';

import Language from '../components/language';

export default function Code({ code, language }) {

console.log(language);

  useEffect(() => {
    Prism.highlightAll();
  }, []);

  const handlClipCopy = (e,code) => {
    e.preventDefault(); 

    navigator.clipboard.writeText(code);
  }

  return (
    <div >
      <h2>{language}</h2>
      <Language/>

      <pre className={styles.root}>
        {/* <button className={styles.copy} href="" onClick={e=>handlClipCopy(e,code)}>Copy</button> */}
        <a className={styles.copy} href="" onClick={e=>handlClipCopy(e,code)}>Copy</a>
        <code className={`language-${language}`}>{code}</code>
      </pre>
    </div>
  );
}
```

**Comment by RunDevelopment** [comment]
Depending on what React framework you use, there could be a lot going on here. For all I know, your page could have a custom router that does a smart refresh that simply clears and re-renders the site, and since the `useEffect(..., [])` has an empty deps array, it doesn't run it again. This is within the rights of React because you are modifying the DOM (`Prism.highlightAll`) without telling React.

Since Prism's highlighting methods inherently modify the DOM, it's not easy to use with React. I'd suggest using the [react-syntax-highlighter](https://github.com/react-syntax-highlighter/react-syntax-highlighter) library.

**Comment by sytpb** [comment]
OK I will check more .   I almost have completed my work for code snippet .

**Comment by sytpb** [comment]
OK I found a solution to fix it . 

App.js
```
  /*const Code = dynamic(() => import("../components/Code"), {
    ssr: false,
  });  */  not work
const wrapper = (entry) => {
//this must inside here   
const Code = dynamic(() => import("../components/Code"), {
    ssr: false,
  });
  const {code} = useCodeFetch({name: entry + ".javascript"});   //get code from file

export default function App() {

  return (
    <div style={{display:"flex", justifyContent: "center",flexDirection:"column"}}>
      <Code code={code} language="html" />
      <Code code={code} language="javascript" />
    </div>
  )
};
```
