### ISSUE TITLE
file extension is incorrectly determined from first (vs last) dot in treeview

### ISSUE THREAD

**Issue by sblive** [PrismJS/prism#3680]
**Information:**
- Prism version: 1.29.0
- Plugins: treeview
- Environment: browser

**Description**
file extension is incorrectly determined from first (vs last) dot in treeview, so e.g. "blah.1.1.2000.docx" incorrectly gets tagged "ext-1-1-2000.docx"

**Example**
"blah.1.1.2000.docx" incorrectly gets tagged "ext-1-1-2000.docx"

**Comment by sblive** [comment]
in the .min.js version i replaced
```
t.push("ext-"+a.join("-"))
```
with
```
t.push("ext-"+a[a.length-1])
```
and it seems to work fine

**Comment by sblive** [comment]
but it seems multiple classes get added, so this will probably break any wanted extension with dot in it (it all becomes e.g. "docx", which in my case i always want), e.g. "tar.gz" will become "gz"

**Comment by Golmote** [comment]
Hi,

Yeah, the multiple classes were intended as a way to maybe highlight .tar.gz differently from just .gz for example. The implementation is intentionally quite naive.

I don't think it matters much if `blah.1.1.2000.docx` gets tagged as `ext-1-1-2000-docx ext-1-2000-docx ext-2000-docx ext-docx` since it's unlikely you would style any of those classes except `ext-docx`.
