### ISSUE TITLE
Thoughts about strings, comments, regexps and other "enclosing" patterns

### ISSUE THREAD

**Issue by Golmote** [PrismJS/prism#412]
Hi there,

As you are aware of, Prism has problems with all patterns that are "enclosing" ones (couldn't think of a better word to describe them...) like strings, comments and regexps.
If we take the JS component, we soon encounter the following problems, regarding comments, strings and regexps :

As far as the tokens appear in the order defined in the components, all is fine :
```javascript
/*te"/st*/ "*/test", /te"st*/;
```
renders as <img src="http://puu.sh/dneVs/3b17d1fdc7.png" />

But if the string comes first :
```javascript
"/*test", /te"st*/;  /*te"/st*/
```
it renders as <img src="http://puu.sh/dneZg/a6ba40c526.png" />

The same kind of problems occurs when the regexp comes before the string, etc.

Currently, Prism will start by matching the full string against the comment pattern, resulting in the creation of a token that will prevent the string to be properly matched on next iteration.

I was thinking lately about making a distinction between "enclosing" patterns and other ones. If enclosing patterns were to be known, it could be possible to overcome the problem by changing the way Prism handles the matching : it could be possible to start by matching the full string against all "enclosing" patterns, and apply the one that matched the closer to the start of the string. I think this would be a safe behaviour for most (if not all) of the languages.

What do you think of this theory ? (And am I making myself clear ?)

**Comment by foo123** [comment]
Check [prism-grammar](https://github.com/foo123/prism-grammar) external parsing add-on for Prism, which uses a grammar to highlight solving all these issues (and more)

**Comment by Golmote** [comment]
Yes I know about your addon. I don't think it's a solution we want to include into Prism though.

**Comment by foo123** [comment]
@Golmote  eventualy if this is going to be solved adequately sth like that add-on will have to be created since simple regexes cannot account for that complexity of laguage, it needs a grammar (or sth equivalent to that, it doesnt have to be the prism-grammar add-on, see [here](https://github.com/foo123/editor-grammar/blob/master/grammar-reference.md#modularity-and-future-directions) as well for further options).

**Comment by Golmote** [comment]
You are right that regexes can't solve the issue completely but it can definitely do better than now. And Prism will keep working this way. We won't add parsing abilities to it.

**Comment by foo123** [comment]
i did not suggest to add that to prism if you dont want to, i just suggested an add-on to prism, as so many other ad-ons, which indeed solves this optimaly. This is already there, no need to add anything new. i specificaly made this for my own needs, but anyone can use it and i suggest others use it. Thats all, relax

**Comment by foo123** [comment]
And anyway to answer your original question and follow Lea's suggestions these tokens like comments, strings regexes i call **block tokens** or **delimited tokens** (and in a refinement, escaped-blocks). So you can just add these two types of special block tokens and solve almost all these issues  Block tokens have a **start** and **end** pattern, when `start pattern` is found it matches up to the `end pattern`, no matter what is within (including multiple lines). `Escaped` block tokens are like block tokens with the exception that their `end-pattern` can appear inside **if it is escaped** else the token closes.Just these additions should meet the requirements by Lea, *some more code* is ok, *some more complexity* is ok, solves almost all such issues. (ps it requires just a small state machine, instead of a more refined parser machine) Cheers!

**Comment by Golmote** [comment]
I'm closing this, since the greedy feature works pretty well.
