### ISSUE TITLE
have to add class to <pre> too with WordPress + W3Totalcache

### ISSUE THREAD

**Issue by JonathanMH** [PrismJS/prism#67]
Hi, I'm using the neatly packaged version from this WordPress plugin http://wordpress.org/extend/plugins/prism-syntax-highlighter/ and I have to add a class like "language-xxxx" to the pre tag too, to get it to work. Seems strange to me, anybody experienced with this issue?

**Comment by loganfranken** [comment]
To be clear, it looks like the WordPress plugin just takes care of adding the Prism assets to the page:
http://plugins.svn.wordpress.org/prism-syntax-highlighter/trunk/wp-prism.php

The real issue here (as @iamdto explained) is that the following two examples render exactly the same:

```
<pre class="language-css"><code>p { color: red }</code></pre>
```

```
<pre><code class="language-css">p { color: red }</code></pre>
```

While the following two examples render differently:

```
<pre class="language-none"><code>p { color: red }</code></pre>
```

```
<pre><code class="language-none">p { color: red }</code></pre>
```

(They match @iamdto's results from above)

I think this is all due to the following line of CSS:
https://github.com/loganfranken/prism/blob/gh-pages/themes/prism.css#L55

Removing the `:not(pre) >` appears to fix it. I can put a PR for this unless there are any objections.

**Comment by loganfranken** [comment]
8030db914a1e7331d245db0b9b787b4364994440 actually fixed this as well (nice work @Golmote!):
https://jsfiddle.net/za1qg99x/

This can be closed.

**Comment by Golmote** [comment]
Indeed. Thanks!

**Comment by JonathanMH** [comment]
So cool, seriously didn't think this would get picked up, amazing work! <3
