### ISSUE TITLE
[website] Chrome blocks download

### ISSUE THREAD

**Issue by LeaVerou** [PrismJS/prism#786]
Related conversation: https://twitter.com/leaverou/status/649309046256758784

**Comment by Golmote** [comment]
For some reason, I can't reproduce the issue with the latest Chrome on my computer... Makes it a bit hard to investigate.

I noticed you suggested using Blobs, so maybe this change in download.js could work?

```javascript
if (typeof Blob !== 'undefined' && window.URL && typeof window.URL.createObjectURL === 'function') {
	var blob = new Blob([redownloadUrl + "\n" + code[type]], {
		type: 'application/octet-stream;charset=utf-8' // Not really sure about this...
	});
	$('#download-' + type + ' .download-button').href = window.URL.createObjectURL(blob);
} else {
	$('#download-' + type + ' .download-button').href = 'data:application/octet-stream;charset=utf-8,' + encodeURIComponent(redownloadUrl + "\n" + code[type]);
}
```

I can't test it, though. Can anybody tell me if it changes anything about the alert in Chrome?

If it doesn't, I suspect the issue could be due to the mime type, couldn't it? We might want to try using `application/javascript` and `text/css` instead. Why did we use `application/octet-stream` in the first place? Was it to force the download in browsers that do not support the `download` attribute?

**Comment by loganfranken** [comment]
I can't reproduce the issue either: I also don't get a warning when downloading the script from the Prism website.

**Comment by LeaVerou** [comment]
I guess it was somehow fixed! Closing.
