### ISSUE TITLE
Most languages not working (e.g. Python)

### ISSUE THREAD

**Issue by fladd** [PrismJS/prism#796]
I selected all languages on the download page, then downloaded the corresponding js and css files.

Only the "built-in" languages are highlighted (e.g. language-clike), but not the extra ones (e.g. language-python does not work!), even though they are part of the js file.

I tried both, development and minified version.

I use the default theme.

**Comment by nauzilus** [comment]
Woah :(

Bison extends the language **c**, but Prism is loads bison first (since `components.js` is in alphabetical order), and the **c** grammar hasn't yet been defined, so fails for everything **bison**.

I think **crystal** is also going to be a problem, because it loads **ruby**.

I'm at work so can't fix this at the moment. I think Prism (specifically `download.js`) is going to need to be smarter about handling dependencies. To make sure they're loaded in an appropriate manner.

**Comment by Golmote** [comment]
This is fixed now #797 is merged.
Thanks for reporting!
