### ISSUE TITLE
`highlight` behavior is surprising on backend

### ISSUE THREAD

**Issue by bebraw** [PrismJS/prism#838]
I'm using `Prism.highlight` on backend for prerendering (no frontend dep anymore). I am using some custom hooks (`before-highlight` and `after-highlight`) to inject custom templating. It was somewhat surprising to notice Prism doesn't allow to use hooks in this case by default.

I did initial hack to enable this functionality. See https://github.com/bebraw/prism/commit/51315ce132b86b9acc88d375b0c87d3575a52a47. It skips most of the hooks but it's enough for my purposes.

This is probably more of a design thing. I can see `Prism.highlightElement` triggers hooks as you might expect. The problem is that it expects a browser environment. Maybe there would be some way to harmonize the API so that you get something that works easily in both without any inconsistencies like this.

**Comment by vkbansal** [comment]
@bebraw I too had same use-case of rendering on node, so I made -> https://github.com/vkbansal/illuminate-js

**Comment by bebraw** [comment]
@vkbansal Thanks! That looks nice. FYI, there's a better language [definition for jsx](https://github.com/survivejs/prism-languages/blob/master/lib/jsx.js). Maybe you can adapt that.

**Comment by vkbansal** [comment]
@bebraw sure will look into it :+1:

**Comment by Golmote** [comment]
Most hooks don't run when `highlight()` is called directly, because they usually use the DOM elements and stuff.

Recently, we added the `before-tokenize` and `after-tokenize` hooks, which _do_ run when `highlight()` is called directly. This should allow you to add custom templating and do all kind of cool stuff with the generated tokens.

See [JSX](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-jsx.js) and [Markup templating](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-markup-templating.js) for examples.
