### ISSUE TITLE
Curious about all the hanging pull requests

### ISSUE THREAD

**Issue by gsklee** [PrismJS/prism#85]
Just wondering what's going on with all the pull requests piling up?

Just saying because this is such a wonderful project, but seeing requests going unanswered since like 9 months ago is really detrimental about attracting future wannabe contributors.

**Comment by jtappa** [comment]
Since this issue is still unresolved, I thought I'd comment here. I'm considering making a language definition and theme for Puppet, but looking at PRs, there's a lot there and several that have been waiting for some time (2+ months). For now I've just broken into MacDown's package contents to edit Prism files to work with Puppet and highlight in my own theme, but I'd like to share this hack more easily with my team, and I'd like to know that if I spent the time to write and polish a new language extension it'd be merged in a reasonable amount of time.

**Comment by mAAdhaTTah** [comment]
I don't know about the open ones, but there have been a ton of [languages added lately](https://github.com/LeaVerou/prism/pulls?q=is%3Apr+is%3Aclosed) so the project is definitely still active and merging PRs.

**Comment by LeaVerou** [comment]
Language definitions generally get merged pretty quickly. The opening PRs are about major changes to the core.

**Comment by jtappa** [comment]
If that's the case, I'll work on a Puppet definition. It's syntactically very close to ruby, so it shouldn't be too difficult. Thanks.

**Comment by LeaVerou** [comment]
I’ve never heard of Puppet before, but if it’s not just *similar* to Ruby, but more like an extension of it, you could look into extending the Ruby definition instead (e.g. look at how JavaScript extends clike)

**Comment by Golmote** [comment]
I'm closing this issue. We're doing our best to handle PRs as they come in.
