### ISSUE TITLE
groovy transforms &lt; in strings into &lt; instead of into < 

### ISSUE THREAD

**Issue by acerberus** [PrismJS/prism#901]
The groovy language highlighter seems to wrongly treat the &lt; html entity when appearing in strings. Consider the following code

`<pre><code class="language-groovy">def a = "&lt;&gt;"</code></pre>`

This should come out as 

`def a = <>`

but instead is transformed into

`def a = &lt;>`

**Comment by zeitgeist87** [comment]
I can confirm this bug. It is because of line 40 in `prism-groovy.js`. `env.content` is already HTML-encoded and `Prism.highlight()` encodes it again.

Unfortunately there is no easy solution for this. I think we should remove the `wrap` hook altogether from `groovy` and implement the same functionality with the `inside` property on the `string`-pattern. I'll work on it.

**Comment by zeitgeist87** [comment]
@acerberus Thanks for reporting this issue!

**Comment by zeitgeist87** [comment]
Should be fixed now.

**Comment by acerberus** [comment]
@zeitgeist87 looks good. thanks for the quick fix.
